### ISSUE TITLE
cluster: creating schema in plugin initializer can lead to duplicates

### ISSUE THREAD

**Issue by mephinet** [gentics/mesh#1013]
Gentics Mesh v1.4.1 on Linux:

Our plugin initialization code is triggered on  project creation. In a clustered setup, all nodes see the project creation event at roughly the same time and start creating the necessary schema. Due to a race condition, this can lead to multiple schemas being created successfully, with different UUIDs, but otherwise identical.
Correct behavior would be for only one node to be successful.

**Comment by Jotschi** [comment]
TODO:
* Check whether conflict occurs when running concurrent request in a multi node cluster setup with quorum 2
* Check whether uniqueness check is run in or outside tx

**Comment by Jotschi** [comment]
Plugins are now initialized sequentially.
