### ISSUE TITLE
Migration/upgrade guide?

### ISSUE THREAD

**Issue by digitalseas** [gentics/mesh#1044]
Hi, 
I am running an app on the Mesh 1.2.1 and I would like to upgrade to 1.4.3 the latest version at this point. Is there guidelines or tutorial on upgrading the system?
Thank you!
-Jack

**Comment by Jotschi** [comment]
You just need to replace the mesh version with the new version and start the server. The migration will automatically be invoked (if needed).

**Comment by digitalseas** [comment]
That's great to know! Thank you, Jotshi!
