### ISSUE TITLE
Graphiql Live Demo Validation errors on /api/v2/demo

### ISSUE THREAD

**Issue by martinbogaert** [gentics/mesh#1054]
## Gentics Mesh Version, operating system, or hardware.
- v1.3.2

## Problem

In GraphQL documentation : https://getmesh.io/docs/graphql/#_graphiql_browser, GraphiQL embed examples are working properly. However there is a link for testing those requests in Graphiql browser on the live demo instance (https://demo.getmesh.io/api/v2/demo/graphql/browser/). The same examples of the one presented in the embed graphiql are returning Validation errors as result. 

Example on https://demo.getmesh.io/api/v2/demo/graphql/browser/

```
{
  node(path: "/yachts/pelorus") {
    fields {
      ... on vehicle {
        name
        description
      }
    }
  }
}
```

is returning on the graphiql browser 

```
{
  "errors": [
    {
      "message": "Validation error of type FieldUndefined: Field 'fields' in type 'Node' is undefined @ 'node/fields'",
      "type": "ValidationError",
      "locations": [
        {
          "line": 33,
          "column": 5
        }
      ]
    },
    {
      "message": "Validation error of type FieldUndefined: Field 'name' in type 'vehicle' is undefined @ 'node/fields/name'",
      "type": "ValidationError",
      "locations": [
        {
          "line": 35,
          "column": 9
        }
      ]
    },
    {
      "message": "Validation error of type FieldUndefined: Field 'description' in type 'vehicle' is undefined @ 'node/fields/description'",
      "type": "ValidationError",
      "locations": [
        {
          "line": 36,
          "column": 9
        }
      ]
    }
  ]
}
```

I see however that the same query is working on the https://demo.getmesh.io/api/v1/demo/graphql/browser/

```
{
  "data": {
    "node": {
      "fields": {
        "name": "Pelorus",
        "description": "Pelorus is the world's nineteenth largest luxury yacht at 115 metres (377 ft) in length."
      }
    }
  }
}

```
Is this behaviour is working as expected ? If it is the case, what are the differences between v1 and v2 that produce these different results ?

**Comment by Jotschi** [comment]
Thanks for the feedback. It seems the link is not correct. We'll update it.

For v2 the correct query would be:

```
{
  node(path: "/yachts/pelorus") {
      ... on vehicle {
    fields {
        name
        description
      }
    }
  }
}
```

**Comment by martinbogaert** [comment]
Thanks for you quick response :)

**Comment by Jotschi** [comment]
Thanks for reporting. I have now updated all examples and links to use the v2 format.
