### ISSUE TITLE
Plugin Deployment may fail due to write quorum not reached

### ISSUE THREAD

**Issue by npomaroli** [gentics/mesh#1061]
## Gentics Mesh Version, operating system, or hardware.
- v1.4.6

## Problem
Some Plugins (like the FormGenerator Plugin) may want to create initial data upon deployment. If this fails, the plugin cannot be deployed

## Reproducer
Create Cluster Setup with 3 Master Nodes, Write Quorum set to "Majority", Prepare Mesh to contain a Project.
Configure FormGenerator Plugin to use that Project.

Start Mesh instances one by one, everytime waiting until the mesh.startup-complete event is fired.

## Expected behaviour and actual behaviour
Expected behaviour: FormGenerator Plugin should be deployed on all three Instances and data should have been prepared

Actual behaviour: Deployment of FormGenerator Plugin on first Instance tries to setup the Project, which fails due to write quorum not reached, therefore the Plugin will not be deployed.
Deployment on second and third instance will work.

**Comment by Jotschi** [comment]
## Ideas

* Defer plugin initialization until cluster is ready
* Add cluster init method which will only invoked by one plugin in the cluster
* Add individual plugin initialization method (current init method).

**Comment by Jotschi** [comment]
Refers to https://github.com/gentics/mesh/issues/1013

**Comment by Jotschi** [comment]
Fixes within 1.4.9 / 1.4.10
