### ISSUE TITLE
Add env setting for imageCacheDirectory

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#1067]
The imageCacheDirectory in `ImageManipulatorOptions` can currently not be configured. We should add an Env to allow this.

**Comment by karowin** [comment]
@Jotschi I was going through this issue, and our understanding is that we have to add the environment variable to the class ImageManipulatorOptions , so that the configuration present in the mesh.yml gets effective. Could you please confirm this.

**Comment by Jotschi** [comment]
@karowin Yes. But I think I may have already fixed this. Let me check.

**Comment by Jotschi** [comment]
@karowin I checked. I did not yet fix it.

https://github.com/gentics/mesh/blob/hotfix-1.4.x/api/src/main/java/com/gentics/mesh/etc/config/ImageManipulatorOptions.java#L27

The field would require the EnvironmentVariable annotation. Additionally I suggest to also add a testcase in the options loader test class:

https://github.com/gentics/mesh/blob/hotfix-1.4.x/common/src/test/java/com/gentics/mesh/OptionsLoaderTest.java#L46

**Comment by karowin** [comment]
@Jotschi thanks for the clarification.
