### ISSUE TITLE
Permission readPublished has no effect

### ISSUE THREAD

**Issue by lakaimdb** [gentics/mesh#1071]
## Gentics Mesh Version, operating system, or hardware.
- v1.4.8

## Operating System
- Windows

## JVM
- I use the docker image gentics/mesh:1.4.8

## Problem
Given: anonymous User has readPublished permission on a node
When: requesting the node via http://localhost:8080/api/v2/:project/nodes/:uuid
Then: the error Nicht genügend Berechtigungen für Objekt \"uuid\" vorhanden. \"read\" wird benötigt. appears 
## Expected behaviour
Given: anonymous User has readPublished permission on a node
When: requesting the node via http://localhost:8080/api/v2/:project/nodes/:uuid
Then: The content of the last published version is returned

**Comment by Jotschi** [comment]
@lakaimdb  By default draft versions are loaded. You need to append the `?version=published` parameter to load the published version. This should handle the read perm correctly.

**Comment by lakaimdb** [comment]
@Jotschi Thank you for the quick response. That does the job, indeed?
