### ISSUE TITLE
GraphQL interface returns draft version node even when permission is restricted to readPublished

### ISSUE THREAD

**Issue by lakaimdb** [gentics/mesh#1074]
## Gentics Mesh Version, operating system, or hardware.
- v1.4.8

## Operating System
- Windows

## JVM
I am using the docker image

## Problem
Given: anonymous user has permission readPublished (and  no other) on a node
When: Invoking 
`https://demo.getmesh.io/api/v2/demo/graphql/browser/#query=%7B%0A%20%20me%20%7B%0A%20%20%20%20username%0A%20%20%7D%0A%20%20node(path%3A%20%22%2Fyachts%2Fpelorus%22)%20%7B%0A%20%20%20%20...%20on%20vehicle%20%7B%0A%20%20%20%20%20%20version%0A%20%20%20%20%20%20isPublished%0A%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A`
Then: Unpublished draft version 1.1 is returned

## Expected behaviour and actual behaviour
Published version 1.0 is returned
![content](https://user-images.githubusercontent.com/11681723/81297086-15d2d980-9073-11ea-8b38-314fe61523aa.png)
![graphql](https://user-images.githubusercontent.com/11681723/81297098-18353380-9073-11ea-9764-ffcb36e223e3.png)
![permissions](https://user-images.githubusercontent.com/11681723/81297118-1cf9e780-9073-11ea-848c-e71ce4ec7a3c.png)

**Comment by Jotschi** [comment]
I think this issue has been reported previously. Afaik there is an issue in the permission handling in graphql node loading. We'll add a testcase for this.

**Comment by Jotschi** [comment]
GraphQL permissions have been reworked in version 1.6.0
