### ISSUE TITLE
Does anyone knows how to run this gentics mesh Java backend in local server so I can hit it with post man the pom.xml is having errors ?

### ISSUE THREAD

**Issue by ShubhamTomar98** [gentics/mesh#1081]
## Gentics Mesh Version, operating system, or hardware.
- v1.3.2

## Operating System

- Windows

## JVM
- Oracle JDK 1.8.0_100
- Open JDK 1.8.0_100

**Comment by mephinet** [comment]
Hi! I would recommend downloading the server jar file from https://maven.gentics.com/maven2/com/gentics/mesh/mesh-server/1.5.1/mesh-server-1.5.1.jar or the demo jar file from https://maven.gentics.com/maven2/com/gentics/mesh/mesh-demo/1.5.1/mesh-demo-1.5.1.jar
Then, you can run the server via `java -jar /path/to/the.jar`. It will be accessible on localhost:8080 where you can access it with postman.
