### ISSUE TITLE
Admin user updated his own permission set of the admin role and restricted him on updating objects

### ISSUE THREAD

**Issue by jrofurtado** [gentics/mesh#1095]
## Gentics Mesh Version, operating system, or hardware.
- v1.4.0

## Operating System
- Linux

## JVM
- Open JDK 1.8.0_100

## Problem
Accidentally, the admin user updated his own permission set of the admin role and restricted him on updating the project. Since it is the only admin user, and we have created a lot of data in this project, how can we recover from this situation? It's necessary to update the OrientDB directly, or is there a better alternative?

**Comment by mephinet** [comment]
Oh, that's a sad story ;-) Unfortunately, Gentics Mesh does not support for a recovery in this case. However, you can solve the issue by using OrientDB Studio. Can you state exactly which permission you are missing? Is it the "read" permission on projects? ?

**Comment by jrofurtado** [comment]
The missing permissions are: create, read, edit, delete

**Comment by Jotschi** [comment]
This should be addressed in Mesh. I can think of the following options:

* Add a command line argument to recover permissions (similar to recover passwords).
* Prevent removal of permissions on "admin" role.
* Make admin role automatically own all permissions.
* Add dedicated admin flag for users and avoid the usage of the role for admin operations. I would favor this option. We currently check for roles with the name "admin". I don't like this approach.

**Comment by Jotschi** [comment]
@jrofurtado 
We just released version 1.5.3 which no longer relies on the `admin` role. Instead the users have a dedicated flag which can be toggled to grant admin perms. Additionally it is now possible to restore the admin user permissions and password via ` java -jar mesh-server-1.5.3.jar -resetAdminPassword admin`.
