### ISSUE TITLE
Read publish permission is not enough to read binary fields

### ISSUE THREAD

**Issue by bernhardriegler** [gentics/mesh#111]
## Gentics Mesh Version, operating system, or hardware.
- v0.9.27

## Operating System
- Linux
- MacOSX
- Windows

## JVM
- Oracle JDK 1.8.0_100
- Open JDK 1.8.0_100

## Problem
A user with a role that has permissions to "read published" nodes will get a "Missing permissions..." response, when trying to load binary fields from a node via the download endpoint.

{meshAPIRoot}/api/v1/{projectName}/nodes/{nodeUuid}/binary/{fieldName}

When the "Read" permission is granted, the user can access the file.

## Expected behaviour and actual behaviour
The permission "read published" should suffice for a user/role to access all fields of a node.

**Comment by Jotschi** [comment]
I have reproduced the issue. Thanks for reporting it.

**Comment by jrmueller13** [comment]
Hi @GenticsDev,
I am facing the same issue with all nodes, i.e. the "readPublished" permission does not suffice to access nodes.

Has this problem ever been fixed?
