### ISSUE TITLE
User node reference cannot updated after being set

### ISSUE THREAD

**Issue by minorgtx** [gentics/mesh#1114]
## Gentics Mesh Version, operating system, or hardware.
- v1.4.3

## Operating System
- Linux

## JVM
- Oracle JDK 1.8.0_251

## Problem
When a user node reference is set one time, it can neither be updated to a new node reference nor be set to null.

## Reproducer
- set a node reference for a user
- try set this node reference to null
- try set this node reference to another node

## Expected behaviour and actual behaviour
- node references should be updated to new node reference or set to null as described in the [documentation](https://getmesh.io/docs/api/#users__userUuid__post)

**Comment by Jotschi** [comment]
This has been fixed in LTS release 1.4.14
