### ISSUE TITLE
Gentics issued API token for users are not JWT conform - they are missing a JTI (unique number) in the claim

### ISSUE THREAD

**Issue by bbelghith** [gentics/mesh#1122]
## Gentics Mesh Version, operating system, or hardware.
- v1.7.1

## Operating System
- Windows

## JVM
- Oracle JDK 11

## Problem
i try to develop a plugin for your solution but i never reach the plugin itself. a jwt-conform token is required and gentics own seems not fullfill it. I receive from the JWT.decode the response that a jti is missing within the claim. this number is part of the JWT specification and important for example to revoke an access token.

**Comment by Jotschi** [comment]
According to RFC7519 is the use of `jti` optional.

> Use of this claim is OPTIONAL.

See https://tools.ietf.org/html/rfc7519#section-4.1.7

**Comment by bbelghith** [comment]
I looked deeper in the code and have to admit that the problem was something else - in the keystore i used the alias "RSA256" - like Keycloak is using it. The vertx library is expecting "RS256" - otherwise there is no match.

**Comment by mephinet** [comment]
Great, so this sounds to be resolved to me. If you disagree, please reopen and let us know what is still there to do. Thanks!
