### ISSUE TITLE
ES Search Admin-Permission checks

### ISSUE THREAD

**Issue by deckdom** [gentics/mesh#1163]
## Gentics Mesh Version, operating system, or hardware.
- v1.6.x

## Problem

When using an User which is marked as "admin", you may still not find certain nodes as long as you don't have explicit permissions for them (Via assigned Groups/Roles).

## Reproducer

Create a new User and mark that User as "admin". Do not assign any permissions.
Now search for a node which usually requires permissions to load (Be sure that "annoymous access" is turned off).

## Expected behaviour and actual behaviour

Since the User is marked as "admin", it should be able to search for any nodes, regardless of permissions, as it does with all other requests/endpoints.

**Comment by plyhun** [comment]
Fixed in 1.10.27
