### ISSUE TITLE
gentics-mesh admin login FAILs behind reverse-proxy; OK at direct connect

### ISSUE THREAD

**Issue by huna02** [gentics/mesh#1179]
## Gentics Mesh Version, operating system, or hardware.
```
release v1.7.7
```

## Operating System
```
grep _NAME /etc/os-release
	PRETTY_NAME="Fedora 33 (Thirty Three)"
	CPE_NAME="cpe:/o:fedoraproject:fedora:33"
uname -rm
	5.11.8-200.fc33.x86_64 x86_64
```

## JVM
```
java -version
	openjdk version "11.0.10" 2021-01-19
	OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
	OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
```

i've installed gentics-mesh v1.7.7 

once installed, and launched, nav to
```
http://127.0.0.1:8443
```

redirects to
```
http://127.0.0.1:8443/mesh-ui/#/login
```

and I can login with admin credentials and use the backend

i'm putting mesh behind an nginx reverse proxy.

in mesh config, I changed
```
config/mesh-ui-config.js

	    var meshUiConfig = {
	        // The URL to the Mesh API
-	        apiUrl: '/api/v2/',
+	        apiUrl: '/cms/api/v2/',
```
my nginx frontend is @ https://example.com

frontend config includes

```
upstream gentics { server 127.0.0.1:8443; }
server {
	...
	location ^~ /cms/ {
		client_max_body_size 400M;

		proxy_pass http://gentics/;
		proxy_redirect / /cms/;

		proxy_buffering  off;
		proxy_connect_timeout  5;
		proxy_http_version  1.1;
		proxy_intercept_errors  on;
		proxy_read_timeout  240;
		proxy_set_header  Host $http_host;
		proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header  X-NginX-Proxy true;
		proxy_set_header  X-Real-IP $remote_addr;
		proxy_set_header  Accept       'application/json';
		proxy_set_header  Content-Type 'application/json';
		proxy_set_header  X-Forwarded-Proto http;
		proxy_set_header  X-SSL-Subject  $ssl_client_s_dn;
		proxy_set_header  X-SSL-Issuer  $ssl_client_i_dn;
		proxy_set_header  HTTPS  off;
		proxy_set_header  Upgrade  $http_upgrade;
		proxy_set_header  Connection  "upgrade";
	}
```

nav to
```
https://example.com/cms
```

correctly redirects to
```
https://example.com/cms/mesh-ui/#/login
```

in browser, I see login UI with 2x "API error" dialogs.
screenshot -> https://i.imgur.com/7BOChN5.png

in logs
```
journalctl -f
	Mar 23 18:46:24 test java[16093]: 18:46:24.375 [] INFO  [vert.x-eventloop-thread-7] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/ HTTP/1.1 304 0 - 2 ms
	Mar 23 18:46:24 test java[16093]: 18:46:24.505 [] INFO  [vert.x-eventloop-thread-0] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/polyfills-es2015.817544d31489c74e9df7.js HTTP/1.1 304 0 - 0 ms
	Mar 23 18:46:24 test java[16093]: 18:46:24.505 [] INFO  [vert.x-eventloop-thread-4] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/assets/config/mesh-ui-config.js HTTP/1.1 200 2393 - 1 ms
	Mar 23 18:46:24 test java[16093]: 18:46:24.505 [] INFO  [vert.x-eventloop-thread-1] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/main-es2015.8c315baaaf165f37b2f5.js HTTP/1.1 304 0 - 1 ms
	Mar 23 18:46:24 test java[16093]: 18:46:24.505 [] INFO  [vert.x-eventloop-thread-5] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/runtime-es2015.907735be6387584d3eca.js HTTP/1.1 304 0 - 1 ms
	Mar 23 18:46:24 test java[16093]: 18:46:24.637 [] INFO  [vert.x-eventloop-thread-3] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/8-es2015.90f6b8dff9e2d0b0b04a.js HTTP/1.1 304 0 - 0 ms
	Mar 23 18:46:24 test java[16093]: 18:46:24.717 [] INFO  [vert.x-eventloop-thread-7] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/7-es2015.daf937d2b3fef64ff7e2.js HTTP/1.1 304 0 - 1 ms
	Mar 23 18:46:24 test java[16093]: 18:46:24.717 [] INFO  [vert.x-eventloop-thread-4] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/6-es2015.3c63dfb222e1e72c90f2.js HTTP/1.1 304 0 - 1 ms
	Mar 23 18:46:24 test java[16093]: 18:46:24.717 [] INFO  [vert.x-eventloop-thread-2] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/1-es2015.b1f5523fe120f034504d.js HTTP/1.1 304 0 - 1 ms
	Mar 23 18:46:24 test java[16093]: 18:46:24.717 [] INFO  [vert.x-eventloop-thread-6] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - GET /mesh-ui/assets/img/logo.svg HTTP/1.1 304 0 - 1 ms
```

login with same, prior working credentials as above FAILs 'quietly'

ONLY an "API Error" dialog in the browser, and *nothing* more in logs

**Comment by plyhun** [comment]
Hi @huna02 ,

Couldn't you please try setting Mesh UI v1?
The "mesh-ui-config.js" file is for Mesh-UI V1 which is reachable via "/mesh-ui-v1", and the config for "mesh-ui2-config.js" is the one for the "/mesh-ui" one. If it works for you, then the problem exists for the Mesh UI v2 only, otherwise it must be a general Mesh problem.

**Comment by huna02** [comment]
> The "mesh-ui-config.js" file is for Mesh-UI V1 which is reachable via "/mesh-ui-v1",

I'm confused.

The default, generated "mesh-ui-config.js" contains
```
	var meshUiConfig = {
		// The URL to the Mesh API
		apiUrl: '/api/v2/',
```
		
v2, not v1.

The docs about v1-vs-v2 api aren't exactly clear or consistent.

**Comment by huna02** [comment]
And, although I _am_ able to login @

https://example.com/cms2/mesh-ui-v1/#/login

I'm unable to EXEC any function once logged in.

E.g.,

- Can't change admin password

if I nav to my admin user in the v1-logged-in-UI @

	https://example.com/cms2/mesh-ui-v1/#!/admin/users/1edd127b4c19e4cca12e52e72e4de32f

and change the password, on submit nothing's changed -- password remains unchanged -- and in logs I see

```
 java[12608]: 08:36:04.848 [] WARN  [vert.x-eventloop-thread-7] [i.v.e.w.h.i.LoggerHandlerImpl] - 127.0.0.1 - POST /api/v2/users/1edd127b4c19e4cca12e52e72e4de32f?lang=en HTTP/1.1 403 0 - 1 ms
```

no other functions, e.g.,

- Can't create new project
- Can't create new user

appear to work either

I notice in the log error,
```
POST /api/v2
```

even though I'm logged in via the v1 ui.

What's the complete procedure for fully disabling v2 api usage across ALL of mesh, and reverting to consistent v1 usage only?

**Comment by deckdom** [comment]
Hi, I think there's a bit of a misconception here.
We have 2 UIs ("/mesh-ui-v1" and "/mesh-ui") and we have an API which also has 2 Versions ("/api/v1" and "/api/v2").
These versions do not relate to each other however.

Currently in the Mesh-UI V2 ("/mesh-ui") you can **not** configure the base-path (Configuration File is "mesh-ui2-config.js").
You can change the base-path in the Mesh-UI V1 ("/mesh-ui-v1") however ("mesh-ui-config.js").

Therefore there's these options available:
* You remove the "/cms" location and serve mesh from the root without an additional base-path
* You use Mesh-UI v1, as this one can be configured to use a different base-path
* Create a PR with a fix for Mesh-UI v2 to include this option

**Comment by huna02** [comment]
> You use Mesh-UI v1, as this one can be configured to use a different base-path

My goal is simply to get to a 1st working instance.

At the moment v2 seems like a problem.  At least one of them.

I'd like to disable it completely to see.

So the same question -- what's the complete procedure for fully disabling v2 api usage across ALL of mesh, and reverting to consistent v1 usage only?

**Comment by deckdom** [comment]
There's no way to disable API or Mesh-UI Versions.
API Version 1 and 2 behave the same way, except for the GraphQL Endpoints.
The only way to "disable" them, is by setting up a reverse proxy which directly forwards requests to a certain version (iE v1) -> /cms -> /api/v1

**Comment by huna02** [comment]
I'll pass on the debate.  v2 doesn't work for this simple use case.

Seems there's no add'l interest in getting info to help fix/clarify this issue, so closing.
