### ISSUE TITLE
Can I connect OrientDB database of mesh?

### ISSUE THREAD

**Issue by suihanhbr** [gentics/mesh#1234]
I find some broken nodes in my mesh instance. I try to access /data/graphdb/storage by OrientDB. But It seems 'finger' is not the correct password for admin, which I found from /config/orientdb-server-config.xml. So what is the default password for the admin of mesh's OrientDB database?

**Comment by bernhardriegler** [comment]
the default password is `admin`

for example this is how to connect in the orientdb console:
```
orientdb> CONNECT plocal:databases/storage  admin admin  
```
