### ISSUE TITLE
Add "curl" to the docker-image

### ISSUE THREAD

**Issue by deckdom** [gentics/mesh#1238]
## Problem

Often times certain operations have to be performed in a cluster which are not cluster aware (`/admin/config` for example).
Therefore, calling the endpoint from within the container is often the only way to do that reliably.

This is however very tricky/impossible, as `curl` isn't preinstalled in the image and you cannot install it, as you lack the permissions for it (image is run under a dedicated user instead of root - which is good, don't get me wrong).

**Comment by bernhardriegler** [comment]
done:
https://github.com/gentics/mesh/commit/d902913a6405154a35d4115af9e593aaefdf5714#diff-7dcfbc368ef61cdb87ff87938d3901a82097fe398633f995dc4ab1cbee761a40

https://getmesh.io/docs/lts-changelog/#v1.6.24

> Docker-Image: The base image has been changed from JRE to JDK to include more tools for analyzing (e.g. creating heap-dumps). The base image has been updated to a newer JDK minor version (11.0.12)
