### ISSUE TITLE
I don't find DaggerMeshComponent in mesh github repo

### ISSUE THREAD

**Issue by meittemarc** [gentics/mesh#134]
I can't start mesh with eclipse because of the absence of DaggerMeshComponent.java. Where can I find the updated project?

**Comment by Jotschi** [comment]
These classes are generated by dagger via APT. Did you setup your IDE accordingly?

https://github.com/gentics/mesh#ide-setup---eclipse

**Comment by meittemarc** [comment]
Thanks Jotschi, dagger generated the classes. 
The administration of the demo (http://localhost:8080/mesh-ui/) works, but the demo not.  The URL http://localhost:8080/demo gives "Not Found" message.

**Comment by Jotschi** [comment]
The demo is a dedicated angular app which is cloned during build time. 
1. cd mesh/demo && git clone https://github.com/gentics/mesh-angular-example demo
2. After the demo has been cloned you can use the DemoRunner class if you want to run the demo. 
The demo itself is just a set of static files.

**Comment by meittemarc** [comment]
Thanks Jotschi.
