### ISSUE TITLE
What is the graph database used?

### ISSUE THREAD

**Issue by idealley** [gentics/mesh#137]
What graph database do you use?

Support for Grakn.AI?

**Comment by Jotschi** [comment]
Gentics Mesh currently only supports [OrientDB](http://orientdb.com). You can read more about the software stack [here](https://getmesh.io/docs/beta/administration-guide.html#_software_stack)

We have plans to also support other vendors like Neo4j, Stardog etc. 
Only databases which support Tinkerpop will ever be supported.
There is no support for Grakn.AI.

**Comment by idealley** [comment]
Thank you!
