### ISSUE TITLE
Binary downloads are not streamed from the filesystem

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh#147]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.3

## Operating System
- Linux

## JVM
- Open JDK 1.8.0_144

## Problem
Currently, when downloading a binary from mesh, the entire file will be loaded into memory and then sent to the client.
This can cause OOM errors for large files and also makes downloads slow.
The code responsible for this can be found here: https://github.com/gentics/mesh/blob/b983dc1aa63eeed5cf2eac8869be28e35c578ac5/core/src/main/java/com/gentics/mesh/core/verticle/node/BinaryFieldResponseHandler.java#L82-L92

## Solution
Add a `getFileStream()` Method to the `BinaryGraphField` interface and use that in the `BinaryFieldResponseHandler`.

**Comment by Jotschi** [comment]
Bug is in BinaryGraphFieldImpl:254
