### ISSUE TITLE
Empty schema crashes index

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#149]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.3

## Operating System
- Linux

## JVM
- Open JDK 1.8.0_131

## Problem
There seems to be an issue with handling an empty schema in the migration.

Steps to re-create:
- Create a Schema without fields
- Assign that Schema to an Project
- Update the Schema with one or more fields in it

This causes the index to crash or at least make the search/graphql-endpoint unavailable, giving out following error message: `"Exception while fetching data (/nodes) : no such index"`

Test Files:
```json
{
    "name": "test_schema",
    "container": false,
    "fields": []
}
```
```json
{
    "name": "test_schema",
    "container": false,
    "fields": [
        {
            "name": "name",
            "type": "string",
            "required": false
        }
    ]
}
```

**Comment by Jotschi** [comment]
I added a testcase for this issue. With the new ES handling this issue is no longer reproducible. Closing.
