### ISSUE TITLE
Gentis Mesh 1.10.5 Demo Won't Start (Docker and JAR File)

### ISSUE THREAD

**Issue by qualitysoftwareguy** [gentics/mesh#1509]
## Gentics Mesh Version, operating system, or hardware.
- v1.10.5 (the demo)

## Operating System
- Linux (Fedora 37)

## JVM
- Open JDK 17.0.6

## Docker
- Docker 23.0.5

## Problem
The Gentics Mesh 1.10.5 demo won't start properly -- applies to both the Docker container and the JAR file.

## Reproducer
Docker:  `docker run -p 8080:8080 gentics/mesh-demo:1.10.5 ` 
JAR File: `java -jar mesh-demo-1.10.5.jar`

## Expected behaviour and actual behaviour
Expected: The demo to start Gentics Mesh 1.10.5

**Actual behavior (for Docker):**
Multiple "error while checking index" errors as shown in the log below:

[gentics-mesh-demo-docker-output.txt](https://github.com/gentics/mesh/files/11411984/gentics-mesh-demo-docker-output.txt)

**Actual behavior (for the JAR file):**
`04:38:40.092 [] INFO  [main] - Configuration file {mesh.yml} was not found within classpath.
04:38:40.093 [] INFO  [main] - Configuration file {config/mesh.yml} was not found within filesystem.
04:38:40.287 [] INFO  [main] - Saved default configuration to file {/home/myuser/Downloads/gentics-mesh/config/mesh.yml}.
04:38:40.287 [] INFO  [main] - Loading default configuration.
04:38:40.292 [] INFO  [main] - Extracting demo data since this is the first time you start mesh...
04:38:45.522 [] INFO  [main] - Demo data extracted to {/home/myuser/Downloads/gentics-mesh/data}
04:38:45.529 [] ERROR [main] - The nashorn classfilter could not be found. You are most likely using an outdated JRE 8. Please update to at least JRE 1.8.0_40`

This error message is strange because `java -version` returns OpenJDK 17.0.6.

**Comment by plyhun** [comment]
Hi @qualitysoftwareguy 
The `1.10.x` versions of Mesh target Java `1.8.x` versions. The support of Java `17+` is guaranteed for Mesh [`2.1.0+`](https://www.gentics.com/cmp/changelog/8.1.0/merged_changelog.html?show=meshsql#7772.GPU-943).
