### ISSUE TITLE
Java 9-12 Support

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#155]
Check whether Gentics Mesh works with Java 9 and whether it can be build and run with Java 9/10/11/12

## Thirdparty Support

* [x] Vert.x -  https://github.com/vert-x3/issues/issues/140 / https://github.com/vert-x3/issues/issues/116 → wait for Vert.x 3.5.0
* [x] Netty - https://github.com/netty/netty/issues/6679 → wait for Vert.x 3.5.0
* [ ] Ferma
* [x] Elasticsearch - Upgrade to 6.0?
* [x] OrientDB - https://github.com/orientechnologies/orientdb/issues/6726
* [x] Dagger 2 - https://github.com/google/dagger/issues/880
* [x] RxJava - Use RxJava 2.0 →wait for Vert.x 3.5.0
* [x] Hazelcast

**Comment by philippguertler** [comment]
Ferma uses Gremlin API. In Gremlin there is a method with the name `_` which is not allowed since Java 9. https://github.com/tinkerpop/gremlin/blob/master/gremlin-java/src/main/java/com/tinkerpop/gremlin/java/GremlinPipeline.java#L1267

**Comment by Jotschi** [comment]
https://ci.gentics.com/view/Mesh/job/mesh/job/dev-java-11/2/

**Comment by Jotschi** [comment]
Released with 0.36.1
