### ISSUE TITLE
Download for Java install packages is not working anymore.

### ISSUE THREAD

**Issue by slavap** [gentics/mesh#1632]
https://getmesh.io/download/

And https://maven.gentics.com/maven2/com/gentics/mesh/mesh-demo/
has NO 2.1.x versions at all.

Does that mean this product is abandoned and not supported anymore?

**Comment by plyhun** [comment]
Hi @slavap 
Mesh is definitely there and is supported for an observable future. What is flawed though, is the documentation and website - there is no demo and no Mesh UI anymore, due to the security issues. I'll update the download page shortly.

**Comment by slavap** [comment]
@plyhun and what supposed to be used instead of Mesh UI? What the point in CMS without UI?

**Comment by plyhun** [comment]
Gentics Mesh is a _headless_ CMS, which main purpose is serving of the structured data over the [REST API](https://getmesh.io/docs/api/#). The graphical UI is an addon, not related to the main content management functionality, which stays around and being actively developed. The [UI](https://github.com/gentics/mesh-ui) still exists in the stale state and can be set up against the existing Mesh installation, if required.

**Comment by slavap** [comment]
@plyhun Headless CMS without admin UI is practically meaningless, how are users supposed to populate content into such CMS?
Take a look at https://directus.io/ or payloadcms.com - the main point of any CMS is to provide users with powerful content editing UI.
