### ISSUE TITLE
Cannot add new user . redirected to Admin user  v0.10.4

### ISSUE THREAD

**Issue by newgeekorder** [gentics/mesh#167]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Operating System
- Windows

## JVM
- Oracle JDK 1.8.0_112

## Problem
Login with Admin user 
Go to the Users Screen. Select "Create New User" 
You are directed to Admin details and not an add user screen 

## Expected behaviour and actual behaviour
An add user form is provided

**Comment by Jotschi** [comment]
The dialog is wrong. I can confirm the issue. If you enter a new username and password you will create a new user when you confirm via update.

**Comment by michaelbromley** [comment]
Fixed in https://github.com/gentics/mesh-ui/commit/63be2efe7dbcc435b3b2c06a8700095f6ec96f7a
