### ISSUE TITLE
Â character in aloha-full.js causes syntax error 

### ISSUE THREAD

**Issue by newgeekorder** [gentics/mesh#168]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Operating System
- Windows

## JVM
- Oracle JDK 1.8.0_112

## Problem

aloha-full.js loaded from jar contains an invalid character 

	function untilNodeForward(node) {
		return untilNode(node) || node.nodeName.toLowerCase() === 'li' || (node.previousSibling && DomLegacy.isEditingHost(node.previousSibling)) ||Â isAlohaBlock(node);
	}

## Expected behaviour and actual behaviour

javascript should load without syntax error

**Comment by Jotschi** [comment]
@newgeekorder I can't confirm the issue. Which browser / browser version are you using?

**Comment by michaelbromley** [comment]
I've seen this on Windows occasionally. We can take a look at this together @Jotschi.

**Comment by Jotschi** [comment]
Fixed with commit https://github.com/gentics/mesh-ui/commit/f408bcfa0998b4a1f746358003b5ce572f6778fe
