### ISSUE TITLE
Old UI: Publishing a node with a slug that already exists does not show a proper error message

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh#173]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Problem
No Error message was shown, even though publishing threw an error.

## Reproducer
* Create a node with a segment field and publish it.
* Create another node with the same segment field and try to save & publish.

## Expected behaviour and actual behaviour
Expected a proper error message.
Did not receive an error at all and it also did not save the node.

**Comment by Jotschi** [comment]
@michaelbromley Do you think it would be hard to display a popup in those cases? The error response already contains an i18n message.

**Comment by Jotschi** [comment]
@philippguertler Those issues should be created in the mesh-ui repo instead.

**Comment by philippguertler** [comment]
Moved to https://github.com/gentics/mesh-ui/issues/9
