### ISSUE TITLE
Apply field validation during publish instead of update

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#175]
Maybe we could save a lot of complexity by asserting schema constrains only when the node is published. Currently the constrains are asserted during each update/create.

Segment Field path uniqueness would still need to be asserted during each update since this would otherwise break the webroot consistency.

**Comment by aschauerhuber** [comment]
This would mean projects not relying on the publishing mechanism (using draft versions only), can't be sure about constraints being asserted...
We need to do more thinking on this
_____________________________

**Comment by Jotschi** [comment]
Validation must happen as-is in order to keep content branches correct. We won't proceed with changes in this area.
