### ISSUE TITLE
Multi-Domain Handling

### ISSUE THREAD

**Issue by aschauerhuber** [gentics/mesh#200]
We need a possibility to allow internal links between nodes of different Gentics Mesh projects.
Link resolving of foreign project nodes must add the hostname.
Mesh links may contain the referenced content release, which defaults to the current release.
Hostname and http(s) configuration will be added to the project create request and stored for each release. Releases can be used to override the default setting.

**Comment by Jotschi** [comment]
## TODO:
* Changelog
* Link resolving 
* Link resolving tests
