### ISSUE TITLE
Unable to access the API after forceful shutdown 

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#206]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Operating System
- Linux

## JVM
- Oracle JDK 1.8.0_141

## Problem
We had an Problem with the server and had to forcefully shut it down. We did __not__ delete the `mesh.lock`-File however which causes mesh to perform a cleanup on the search-index.
This however is done before the server is started up completely and prevents any calls to the API.

Since we have a lot of nodes managed with it, it takes a long time to do that re-indexing (aprox. 3-4h) which is a major downtime for the customer.

## Expected behaviour and actual behaviour
That the search-index is not getting completely wiped and then re-indexed, but should be checked if any data is corrupt/wrong.
Then it should do that **after** the general startup and perform the re-indexing simular to the way a migration does it, by not dumping the existing index and setting it up from the grounds.
Rather it should update the index as soon as it is processed and keep the old index alive until everything is done.

**Comment by Jotschi** [comment]
Index handling has been refactored.
