### ISSUE TITLE
Out of Memory Exception when recursively deleting nodes

### ISSUE THREAD

**Issue by elbird** [gentics/mesh#207]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Operating System
- MacOSX

## JVM
- Oracle JDK 1.8.0_100

## Problem
When deleting a folder-node containing about 28.500 children (in several sub folders) mesh will take up a lot of system resources and never finish deleting the nodes because it runs into a Out of Memory Exception (see attached log output)
[error.log](https://github.com/gentics/mesh/files/1496043/error.log)

## Reproducer
Started mesh with 2g of mem
` /usr/bin/java -jar -Xmx2048m /Users/sebastian/gitprojects/wkw-kofl/portal/mesh-home/mesh-server.jar`

**Comment by Jotschi** [comment]
I think the transaction size exceeds the heap memory and thus an OOM happens.

**Comment by Jotschi** [comment]
@sebastianvogel Can you provide a oom dump?

**Comment by Jotschi** [comment]
Delete handling performance has been greatly optimized with release of 0.32.0 - closing this issue.
