### ISSUE TITLE
Numbers get truncated to 3 decimal places

### ISSUE THREAD

**Issue by sebastianvogel** [gentics/mesh#209]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Problem
When saving a number with more than 3 decimal places e.g. 0.123456, the number will be truncated to 3 decimal places

## Reproducer

Update request POST to \<projectName\>/node/\<UUID\>
```
{
	"uuid": "<UUID>",
	"language": "en",
	"fields": {
		"numberField": 16.35743564
	},
	"version": "1.0"
}
```

Response from server with truncated number
```
{
	"uuid": "<UUID>",
	"language": "en",
	"fields": {
		"numberField": 16.357
	},
	"version": "1.1"
}
```

## Expected behaviour and actual behaviour

I expect to be able to post numbers with many decimal places to mesh. Imho the string conversion methods of BigDecimal.toString() and BigDecimal.valueOf(String) would be best to store and retrieve numbers for Mesh internally. (instead of NumberFormat - if conversion to String is needed)

**Comment by Jotschi** [comment]
Resolved with 0.11.5
