### ISSUE TITLE
Out Of Memory Exception when processing migration job

### ISSUE THREAD

**Issue by sebastianvogel** [gentics/mesh#212]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Operating System
- Linux (RedHat 7)

## JVM
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)

## Problem
When running a migration our mesh-instance runs constantly runs into OOM Exceptions. We use the default JVM MaxMemory of 2g.

see attached Stacktrace in log file 
[oom.txt](https://github.com/gentics/mesh/files/1501713/oom.txt)

Here you can find the heap dump:
https://filebox.apa-it.at/index.php/s/6wfhl7HjbwazvMk (Please contact me directly for the download pass)

**Comment by Jotschi** [comment]
A FermaGremlinPipeline kept a lot of references (131k) to graph vertices (NodeGraphFieldContainers) in the heap and thus no more space was free for other stuff. The ferma gremlin pipeline applied a deduplication filter pipeline and thus a map was generated which contained all the data.

Assumed source: MicronodeMigrationHandler:68
Confirmed source lies deeper: MicroschemaContainerVersionImpl#getDraftFieldContainers

The traversal contains the dedup call and this adds the deduplication pipeline filter.

Fix: Remove dedup and add a check to skip micronodes which have already been migrated

**Comment by sebastianvogel** [comment]
Fixed with Pull request #215
