### ISSUE TITLE
mesh-ui node creation popup has no scroller

### ISSUE THREAD

**Issue by clems159** [gentics/mesh#218]
## Gentics Mesh Version, operating system, or hardware.
- v0.11.2

## Operating System
- MacOSX Sierra

## JVM
latest open jdk 1.8

## Problem

When there is a lot of nodes schema and we want to create on, we can't dropdown list (no scroller) no find the appropriate node type

## Reproducer

![image](https://user-images.githubusercontent.com/6388506/33433616-8f94f446-d5dc-11e7-9ced-f8fef7437dd7.png)

## Expected behaviour and actual behaviour

have a scroller or node creation wizard

**Comment by Jotschi** [comment]
@clems159 Thank you for the report. We are currently reworking the Mesh UI and hope to release a new version in Q1 2018. We'll make sure that this design issue will be fixed in that version.

**Comment by Jotschi** [comment]
@michaelbromley Do you think we could fix this issue in the current version of the mesh UI?

**Comment by clems159** [comment]
we can do it too, where is the mesh-ui angular app located?

**Comment by clems159** [comment]
ok we found it gentics/mesh-ui

**Comment by Jotschi** [comment]
@clems159 The beta branch contains the currently used version. You can base your changes upon that branch - https://github.com/gentics/mesh-ui/tree/beta

**Comment by jeansaigne** [comment]
Hi, did you make any change to fix this issue ?

**Comment by Jotschi** [comment]
Hi @jeansaigne 
no, we have not yet addressed this issue. We try to focus on the new UI as much as possible and take this issue into account when building the new UI.

**Comment by cschockaert** [comment]
add a PR, can you review it?
https://github.com/gentics/mesh-ui/pull/163

**Comment by Jotschi** [comment]
We have now addressed the issue. The fix is included in 0.24.1
