### ISSUE TITLE
Search nodes by nested field values doesn't work (elastic search query is broken)

### ISSUE THREAD

**Issue by mkozhukharenko** [gentics/mesh#228]
# Validation for lists of nodes doesn't work

### Gentics Mesh Version, operating system, or hardware.
- v0.11.3

### Operating System
- MacOSX

### JVM
- Open JDK 1.8.0_111

### Problem

Elastic search query doesn't work as expected: it doesn't work if you try query data by nested field. 

### Reproducer

My node have the next shape ( I omitted some field for convenience):
```
{
            "uuid": "a35c26669bb341269c26669bb3f12695",
            "tags": [
                {
                    "name": "4K/8K Video",
                    "uuid": "3c9e7edf70844f189e7edf7084df18e8",
                    "tagFamily": "telecoms"
                }
            ],
            "schema": {
                "name": "Inteview",
                "uuid": "6e64811774f24917a4811774f24917b4",
                "version": "2.0"
            },
            "container": false,
            "displayField": "title",
            "fields": {
                "title": "Parallel Wireless Adds 2G Capabilities to Their 3G/4G End-to-End Innovative SDR Solution",
                "slug": "parallel-wireless-adds-2g-capabilities",
                "description": "<p></p>",
                "category": [
                    {
                        "uuid": "b4b6ea58b3d84bdab6ea58b3d81bda83",
                        "path": "/api/v1/krusche/webroot/telecoms/analysis/interviews"
                    }
                ]
            }
     }
```
If I run my query to fetch all articles with exact category:
```
{
  "query": {
    "nested": {
      "path": "field.category",
      "query": {
        "bool": {
          "must": [
            { "match": { "field.category.uuid": "b4b6ea58b3d84bdab6ea58b3d81bda83" }}
          ]
        }
      }
    }
  }
}
```

I got an error
```
{
    "i18nParameters": [
        "SearchPhaseExecutionException[all shards failed]"
    ],
    "properties": {
        "cause-0": "QueryParsingException[[nested] failed to find nested object under path [field.category]]"
    },
    "type": "generic_error",
    "message": "An error occurred while handling query."
}
```

I tried a tons of different queries to fetch nodes (articles schema) by category (node uuid). Some of them have returned uncaught exceptions, another - empty data.

If you try to run query example 'Search nodes by micronode field values' from the [documentation](https://getmesh.io/docs/beta/features.html#contenttree) - the uncaught exceptions will be returned as well.

At a same time it's possible to query data by tags, e.g.:
```
{
  "query": {
    "nested": {
      "path": "tags",
      "query": {
        "bool": {
          "must": [
            { "match": { "tags.name": "SDN" }}
          ]
        }
      }
    }
  }
}
```
## Expected behaviour and actual behaviour

Elastic search should return filtered data and should not through an Exception.

**Comment by Jotschi** [comment]
@mkozhukharenko Node lists have no nested properties.

Take a look at the documentation which includes an example for a indexed document:

https://getmesh.io/docs/beta/features.html#_nodes

```
…
    "nodeList" : [ "ac1541d0a4cf4c309541d0a4cf5c3020", "ac1541d0a4cf4c309541d0a4cf5c3020", "ac1541d0a4cf4c309541d0a4cf5c3020" ],
…
```

A valid query for a node list would thus be: 

```
{
 "query":{
   "term":{
      "fields.nodelist" : "8e4a0bcfa496495a8a0bcfa496c95a96"}
   }
}
```

Unfortunately the REST model does not 100% match up with the indexed document (Due to ES limitations and design choices). I'll check whether it would be possible to include a bit more information of the referenced nodes.

**Comment by mkozhukharenko** [comment]
@Jotschi thanks for sp fast response!

My node list have a different shape:
```
…
    "nodeList" : [ {"uuid": "ac1541d0a4cf4c309541d0a4cf5c3020"}, {"uuid": "ac1541d0a4cf4c309541d0a4cf5c3020"}, {"uuid":"ac1541d0a4cf4c309541d0a4cf5c3020"} ],
…
```

### Here is my schema

On UI:

![article_schema_node_list](https://user-images.githubusercontent.com/9365923/33731023-7c6dde56-db8a-11e7-984a-0143d656e6bf.png)

And JOSN
```
{
	"name": "article",
	"displayField": "title",
	"segmentField": "",
	"urlFields": [],
	"container": false,
	"fields": [
		{
			"name": "sub_category",
			"label": "Sub category",
			"required": true,
			"listType": "node",
			"type": "list",
			"allow": [
				"sub_category",
				"category"
			]
		},
		...
	]
}
```

### Here is my data

On UI:

![article_with_node_list_ui](https://user-images.githubusercontent.com/9365923/33731080-a92ffc9e-db8a-11e7-858f-03b0f33a147f.png)

and RAW

![node_list_data_raw](https://user-images.githubusercontent.com/9365923/33731094-b00dbb0a-db8a-11e7-9c90-bb67c83cc8be.png)


---

and the *Search nodes by micronode field values* example from documentation 

```
{
  "query": {
    "nested": {
      "path": "fields.vcardlist",
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "fields.vcardlist.fields.firstName": "Joe"
              }
            },
            {
              "match": {
                "fields.vcardlist.fields.lastName": "Doe"
              }
            }
          ]
        }
      }
    }
  }
}
```
throws an Exception which I described in the docs (even if I change nested fields to different ones). 

Can you help me to figure out this problem? I might miss something..

**Comment by Jotschi** [comment]
@mkozhukharenko I updated the demo instance to reflect your setup:

* I updated the vehicle schema to also include a node list (imageList).
* Next I updated the _DeLorean DMC-12_ node to include an _imageList_ which contains three nodes:

https://demo.getmesh.io/api/v1/demo/nodes/adaf48da8c124049af48da8c12a0493e

Data of the node:

```json
…
   "imageList" : [ {
      "uuid" : "b1a975d9391a4daaa975d9391abdaa4f"
    }, {
      "uuid" : "3db965753d9d41f0b965753d9da1f019"
    }, {
      "uuid" : "ec2f5106764c4d94af5106764ccd948a"
    } ]
…
```

Next I invoked the search query to locate those nodes which have the node b1a975d9391a4daaa975d9391abdaa4f in the image list:

*POST https://demo.getmesh.io/demo/search/nodes*

```
{
 "query":{
   "term":{
      "fields.imageList" : "b1a975d9391a4daaa975d9391abdaa4f"}
   }
}
```

Could you perhaps describe your usecase and what you actually want to achieve? You could try to setup your usecase in our demo instance. The instance will only be resetted on demand and once a new release is published.

**Comment by mkozhukharenko** [comment]
@Jotschi thanks a lot, it works! 🎉 

But I think that this query in a [docs](https://d26dzxoao6i3hh.cloudfront.net/items/2Y2B0H3k2N443r3N341r/Image%202017-12-11%20at%2010.01.05.png?v=52ee976f) should me updated cause it doesn't work

--- 

I'd like to raise another issue in this topic:
Since you don't expose not a native Elastic search result and [modifies query internally before it's being passed to elastic search](https://github.com/gentics/mesh/blob/master/elasticsearch/src/main/java/com/gentics/mesh/search/index/AbstractSearchHandler.java#L97-L113) - it must be explained. I can't see Elastic search data modeling which may help to construct correct complex query ((

I think that the best way is to get rid of this redundant layer layer between user (developer) and Elastic search. It make me to guess a query structure rather that design  it confidently.

**Comment by Jotschi** [comment]
@mkozhukharenko Great to hear that it is now working. I'll update the docs to make the query handling easier to understand. Did the modification of the query by mesh cause any issue for you?

You can by the way also use the `/api/v1/:projectName/rawSearch/` endpoint which will not transform the resulting query response. (It will still apply the internal query transformation)

We plan on decoupling Elasticsearch and Gentics Mesh in the near future. This way it will be possible to run a dedicated ES server to which Gentics Mesh can connect and store its data.
