### ISSUE TITLE
Fix version chain handling

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#231]
Currently the version chain handling has some issues.
Deletion of language variants causes chain inconsistencies.

Deletion handling could be implemented differently:

* The initial edge will be updated once a new language variant is being created for a node to which the language was removed earlier.
* In this case the current version chain for the initial edge will be cleaned and the initial edge will be updated to point to the new version chain.
The cleaning of the version chain must stop as soon as another initial edge for a different release is encountered. We don't want to affect other releases by this action.

Tasks:

 * [x] Change current version handling. Versions should be located starting from the draft/publish version. Currently the version is being located using the initial version. This will cause issues when dealing with multiple releases.
* [x] Add a consistency check for dangling version chains
* [x] Add a change which updates the initial edge and sanitizes the version chain. The chain must be sanitized in a way that older versions will be removed. The process must not remove versions which are referenced by other releases. Thus the process must stop once it encounters a version which is referenced by an initial release edge from another release.

**Comment by npomaroli** [comment]
I think that's fixed with #383
