### ISSUE TITLE
Production ready ?

### ISSUE THREAD

**Issue by jeansaigne** [gentics/mesh#258]
I'm part of a big enterprise, and i need to know if you think your CMS is production ready yet ?

**Comment by Jotschi** [comment]
I think this depends on what you want to do with Gentics Mesh. Keep in mind that we are still developing Gentics Mesh and are also modifying some features.

Breaking changes will be listed in the changelog. Although we are still in beta there already exists an upgrade path.
That means you can always update a released Gentics Mesh version to a newer version even while in beta.

We already use Gentics Mesh for some sites. One example is [APA OTS Video](https://www.apa-ots-video.at/) which is an Austrian video platform.

A new UI version is currently being build. We aim to release Gentics Mesh 1.0 with the new UI in the first half of this year.

Let me know whether you have any further questions.
