### ISSUE TITLE
GraphQL: Filtering/Sorting

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#27]
It should be possible to apply filtering and sorting to each endpoint that returns a list of items.

**Comment by philippguertler** [comment]
Still open:

- [ ] List Fields
- [ ] Node References
- [ ] Micronodes
- [ ] Binaries
- [ ] Filtering for other types (Schemas, Users, etc.)

**Comment by plyhun** [comment]
https://github.com/gentics/mesh/pull/1223
Not yet merged because of perf penalties.
