### ISSUE TITLE
Fix Focal Point Resize Error

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#272]
Focal Point crop/resize will not happen if no fpx / fpy has been specified. The action will silently fail and return the original image.

https://demo.getmesh.io/api/v1/demo/webroot/images/ford-gt.jpg?w=800&h=600&crop=fp&fpdebug=true

**Comment by tpusztaiGentics** [comment]
There is another issue, which can cause a focal point zoomed image to be skewed:
https://demo.getmesh.io/api/v1/demo/webroot/images/ford-gt.jpg?w=400&h=400&crop=fp&fpx=0.5&fpy=0.5&fpz=2&fpdebug=true

**Comment by tpusztaiGentics** [comment]
When a target width and height are specified, the zoom does not seem to be performed properly. The above URL requests 2x zoom, but the actual seems is much less.
