### ISSUE TITLE
Validation of (micro)-schemas isn't strict

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#278]
## Gentics Mesh Version, operating system, or hardware.
- v0.15

## Problem

Validation of the (micro)-schema isn't completely strict and allows potential pitfalls/weird configurations:

- Field names allows `number` and `boolean`
- The (Micro-)Schema name allows  `boolean`
- The `container`-property allows `number` (int) and `boolean`
- The `required`-property in fields allows `number` (int)
- The `label`-property in fields allows `number` and `boolean`
- The `allow`-property in fields allows `number` and `boolean`-Arrays
- `elasticsearch`-Settings of an Field aren't checked property (Allows input such as: `"elasticsearch": { "test": true }`)

Not sure if these are intentional since most of these are simply getting interpreted as strings.

**Comment by Jotschi** [comment]
http://stackoverflow.com/questions/18154983/how-do-i-validate-incoming-json-data-inside-a-rest-service

**Comment by philippguertler** [comment]
Type coercion into string is the default behaviour of Jackson. There is no default way in Jackson to disable that (https://stackoverflow.com/questions/12546810/how-to-enable-strict-type-parsing-for-jackson).

Also changing this now could potentially be a breaking change, so we will leave it for now.
