### ISSUE TITLE
Logout doesn't work correctly

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#282]
## Gentics Mesh Version, operating system, or hardware.
- v0.14.2

## Problem

At least in v0.14.2 there seems to be an Issue with the Cookie Header. When you login to mesh, the `mesh.token`-Cookie is saved on the root-path (`Path=/`)
However, when you go to the logout endpoint, the Path is set to `Path=/api/v1/auth`

## Reproducer

- Login with any user
- Logout with the user
- Take a look at the `/auth/me` endpoint

**Comment by Jotschi** [comment]
TODO: 
* add delete cookie in logout response
