### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by itbrandonsilva** [gentics/mesh#330]
Considering there isn't any hub or direction on where to seek support other than posting issues here, Gitter seems like a really easy way to get started fostering some form of community, as well providing a place where people can solve relatively simple problems that don't need to be github issues.

Is there an accessible mesh community hub that I'm unaware of?

**Comment by Jotschi** [comment]
We currently only have github issues and stackoverflow. I think gitter would be a good option for smaller feedback and Q/A's. I'll check what we can do about it.

**Comment by Jotschi** [comment]
We now have setup a [gitter channel](https://gitter.im/gentics/mesh) for Gentics Mesh.

**Comment by itbrandonsilva** [comment]
Nutty timing. You closed the issue as I was about to ask for an update. Thanks! I'll be in there often.
