### ISSUE TITLE
Job Properties ignore Schema-Type

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#336]
## Gentics Mesh Version, operating system, or hardware.
- v0.17.x

## Problem

When getting the Job-List, I noticed that the Job's Properties-Field doesn't differentiate between a schema and a microschema. It'll simply output both infos even of only one can apply.
Bigger evil is that it's outputting data which is incorrect, as the UUID/Name are from the wrong type.

## Reproducer

Perform a schema change which kicks on a migration. Then load the job-list via `admin/jobs`

## Expected behaviour and actual behaviour

Schema-Migration Jobs should not have a `microschemaName`/`microschemaUuid` field, and Microschema-Migration Jobs should not have a `schemaName`/`schemaUuid` field in the properties.

**Comment by Jotschi** [comment]
This has already been fixed

**Comment by Jotschi** [comment]
https://getmesh.io/docs/beta/changelog.html#v0.17.1
