### ISSUE TITLE
Problem setting role permissions from UI

### ISSUE THREAD

**Issue by afilimonov** [gentics/mesh#340]
## Gentics Mesh Version, operating system, or hardware.
- v0.17.1

## Operating System
- Linux
- MacOSX
- Docker

## JVM
- Oracle JDK 1.8.0_100

## Problem
Cannot set role permissions on project using mesh UI.

## Reproducer
Start new mesh or mesh demo instance. Login as admin
Create project ‘test’
Go to roles page and select anonymous role
Expand project permissions and chech ‘read’ box on ‘test’ project 
Navigate away from roles page
Go back to roles/anonymous/projects
‘read’ checkbox on ‘test’ is unchecked

## Expected behaviour and actual 
‘read’ permission on ‘test’ project is checked

**Comment by Jotschi** [comment]
Hi,
I just tested this case in the demo instance:
https://demo.getmesh.io/mesh-ui/#!/projects

I created the project and granted the perm to the anonymous role. I checked whether the change was persisted. 
https://demo.getmesh.io/api/v1/test

Could you check whether you see any error in the browser console? 
We will improve the error handling in the new UI which is currently being build.

**Comment by Jotschi** [comment]
@afilimonov I was able to reproduce the issue. This is just a UI problem. It seems that the state of the flag is not correctly updated in the client. The change is correctly send to the server and you will also see the correct flag in the UI if you reopen the UI. We are currently working on the new UI and will make sure that this issue will not occur there.

**Comment by afilimonov** [comment]
This seems to happen to other permissions to eg schemes. Only node permissions work as expected.

**Comment by philippguertler** [comment]
@afilimonov It seems that the internal state of the permissions in the UI does not seem to be updated when changing them. As @Jotschi said, in the new UI we will make sure that the permissions are displayed correctly.

**Comment by afilimonov** [comment]
Yes I can see 'read' permission on 'test' project in UI. What I noticed though is that I cannot view root node using webroot:

curl https://demo.getmesh.io/api/v1/test/webroot/
{
  "i18nParameters" : [ "0f315afa473f4da3b15afa473f1da3ac" ],
  "properties" : { },
  "type" : "generic_error",
  "message" : "Missing permissions on object \"0f315afa473f4da3b15afa473f1da3ac\"."

When I try to get navigation menu I also get permssion error:

curl https://demo.getmesh.io/api/v1/test/navroot/
{
  "i18nParameters" : [ "0f315afa473f4da3b15afa473f1da3ac" ],
  "properties" : { },
  "type" : "generic_error",
  "message" : "Missing permissions on object \"0f315afa473f4da3b15afa473f1da3ac\"."

Anonymous role has readPublished node provilege on test but not read. Is it intended behavior?

**Comment by Jotschi** [comment]
@afilimonov You also need to assign the permissions on the nodes of the project. You can also do this within the UI and apply recursive permissions.
![nodeperm](https://user-images.githubusercontent.com/326605/37407413-e1683dbe-2799-11e8-9e04-559f0fb7c407.png)

**Comment by afilimonov** [comment]
Do I need read privilege to get navroot working? This seems odd. My understanding it will read bot published and unpublished nodes is this correct? Is there way to list only published nodes?

**Comment by Jotschi** [comment]
@afilimonov By default the visibility scope is set to "draft" this means that you need to append the version parameter `?version=published` if you want to only see the published nodes. Hope this helps.

**Comment by afilimonov** [comment]
Yes this is very helpful
