### ISSUE TITLE
Node's unpublished state is not represented in the UI

### ISSUE THREAD

**Issue by DevNils** [gentics/mesh#345]
## Gentics Mesh Version, operating system, or hardware.
- v0.17.1

## Operating System
- Linux (Ubuntu 16.04)

## JVM
- Open JDK 1.8.0_151

## Problem
When you unpublish a published node with a delete request via /{project}/nodes/{nodeUuid}/published, the unpublished state ist not represented in the UI of the CMS. You will see it in the API payload but not in the CMS ui.

## Reproducer
- Publish a node
- Unpublish it with the rest API
- Query the node with API and check the JSON payload
- Check the node state in the CMS UI

## Expected behaviour and actual behaviour
You will see that it shows "PUBLISHED" in the UI although the node has an unpublished state in the JSON payload.

**Comment by Jotschi** [comment]
@DevNils Thanks for the report. This is a bug in the etag generation. I was able to reproduce it. The browser will use the node response from the browser cache instead of re-loading the node from mesh.  Should be fairly easy to fix. I'll hopefully be able to include it in the next release.

**Comment by Jotschi** [comment]
@DevNils Fix is merged and will be included in the next release.

**Comment by Jotschi** [comment]
The fix has been released.
