### ISSUE TITLE
Use the same UUID for dummy data

### ISSUE THREAD

**Issue by leonadler** [gentics/mesh#347]
- Mesh v0.17.3
- Linux 4.9.86
- Oracle JRE 9.0.4

## Problem

When `GET /api/v1/raml` is requested twice, the output changes due to different UUIDs.

We use the RAML that is output by mesh to generate TypeScript models & documentation,
which produces a different file even for the same version. When rendering the interfaces
from a different version, spotting the differences (and necessary changes) in the git diff is complicated [(example diff from updating the models from 0.13.1 -> 0.17.1)](https://github.com/gentics/mesh-ui/commit/0d3bf9a52dae71ee4561367bceda5837e15188e0#diff-595cdfec08569ad0f8fb39f32ca7df6e).

## Reproducer

Variant A:

1. Start Mesh
2. Request http://localhost:8080/api/v1/raml, save as 1.raml
3. Request http://localhost:8080/api/v1/raml again, save as 2.raml
4. The two files are different

Variant B:
1. Start Mesh
2. Request http://localhost:8080/api/v1/raml, save as 1.raml
3. Stop Mesh
4. Restart Mesh
5. Request http://localhost:8080/api/v1/raml again, save as 2.raml
6. The two files are different

## Expected behaviour and actual behaviour

Variant A:
The raml output the same when re-requested.

Variant B:
The raml output the same when re-requested after restarting Mesh.

**Comment by Jotschi** [comment]
We already have the plan to map the RAML examples to existing demo data.

**Comment by leonadler** [comment]
![2018-03-16-104022_1344x365_scrot](https://user-images.githubusercontent.com/8845620/37513854-884fee3e-2906-11e8-89e2-ba8d8fbbe44c.png)

**Comment by Jotschi** [comment]
UUID will be pinned with the next release
