### ISSUE TITLE
Spaces in path cause MeshRestClient to never return

### ISSUE THREAD

**Issue by elbird** [gentics/mesh#360]
## Gentics Mesh Version, operating system, or hardware.
- v0.17.3

## Problem
Calling the webroot method with a path string containing space will cause the MeshRestClient to never return.

## Reproducer
Call to:
MeshRestClient.webroot("my-project", "/path with spaces", ...

**Comment by Jotschi** [comment]
MeshRestHttpClientImpl:713 - @elbird  Please add a fix
