### ISSUE TITLE
Login token is not invalidated on logout

### ISSUE THREAD

**Issue by DevNils** [gentics/mesh#403]
## Gentics Mesh Version, operating system, or hardware.
- v0.19.2

## Operating System
- Linux 16.04

## JVM
- Open JDK 1.8.0_151

## Problem
The token you will receive when you call /api/v1/auth/login is still valid after a /api/v1/auth/logout call.

## Reproducer
Make a post request with your credentials like:
```
curl --request POST \
>   --url http://url_to_mesh/api/v1/auth/login \
>   --header 'content-type: application/json' \
>   --data '{
> "username": "user",
> "password": "pw"
> }'
```
You will receive your login token. Take the token and make a get request like /auth/me
```
curl --request GET \
>   --url http://url_to_mesh/api/v1/auth/me \
>   --header 'authorization: Bearer your_token'
```
You will receive your user infos. Now logout:
```
curl --request GET \
>   --url http://url_to_mesh/api/v1/auth/logout \
>   --header 'authorization: your_token'
```
If you call /auth/me again your token is still valid and you will receive your user infos.

## Expected behaviour and actual behaviour
I would expect that token is invalid after calling /auth/logout but maybe I am wrong.

**Comment by Jotschi** [comment]
JWT tokens can't be invalidated. They are valid as long as the token is not yet expired. This is a drawback when using JWT. The logout endpoint currently only deletes the cookie which contains the token.

The only way this could be solved would be to implement a blacklist and add the token to that blacklist.

**Comment by DevNils** [comment]
Thanks for the information.

**Comment by Jotschi** [comment]
@DevNils FYI: The API token however can be invalidated by issuing a new token. We apply a blacklist for the  API.

**Comment by Jotschi** [comment]
I'm closing the issue. Let me know if you have any further questions. Feel free to open another issue.
