### ISSUE TITLE
creating new node with language set to 'de' creates

### ISSUE THREAD

**Issue by virbas** [gentics/mesh#404]
## Gentics Mesh Version, operating system, or hardware.
- v0.19.2

## Operating System
- MacOSX

## Problem
when POST'ing to /{project}/nodes/ (creating a new node) with language set to 'de', response does not contain 'language', 'version', 'displayField', 'displayName', 'editor' and 'tags' fields. 'fields' is returned as an empty object {}

## Edit
Same applied for updating the binaries: '/{project}/nodes/{nodeUuid}/binary/{fieldName}'

**Comment by Jotschi** [comment]
That works as designed since by default Mesh tries to load the english node. Run the same POST request and append `?lang=de` and it should work. This is in fact something which we should try to change. I agree that a dev would expect a different response.

**Comment by Jotschi** [comment]
@npomaroli , @philippguertler Should we be perhaps always return the created node content and discard the query param or at least discard the default language setting in this case? wdyt?

**Comment by virbas** [comment]
It would be fine just passing the ?lang=de. However, the confusing part is that the response contains no 'language' param at all. One would expect either a full version of the node for the default language or an error code with a message that the default language was not created yet.

**Comment by philippguertler** [comment]
@Jotschi In my opinion, when you create a resource in REST, the response should be the created resource. This should be consistent with all create requests. So in this case the query language parameter should be ignored.
