### ISSUE TITLE
Nodes are not getting indexed

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#409]
## Gentics Mesh Version, operating system, or hardware.
- v0.19.2

## Problem

Sometimes it happens that Nodes are not getting indexed to ES. The `/search/sync` endpoint does apparently detect these issues, but doesn't resolve them correctly. I ran the Sync two times and it still finds nodes which aren't indexed.

## Expected behaviour and actual behaviour

That all nodes are getting indexed accordingly

**Comment by Jotschi** [comment]
You can however resolve the issue by invoking clear and sync.
