### ISSUE TITLE
WebRoot Resolving Performance

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#418]
Resolving a webroot path is very slow. We need to check how this could be optimized.

**Comment by philippguertler** [comment]
I tested performance of webroot by calling the endpoint 1000 times concurrently and compared it to the node by uuid endpoint. The difference was about 2 ms per request, so it's safe to say that the webroot requst is not very slow, compared to other means.

**Comment by philippguertler** [comment]
I have looked at the performance again and found out that it gets much slower when there are a lot of nodes. There is already an index for nodes in webroot, but this index is not used for reading. I will create a fix for that.
