### ISSUE TITLE
Inconsistent behavior with empty allow in schema field

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh#431]
## Gentics Mesh Version
- v0.21.1

## Problem
Micronode fields and micronode list fields behave differently when the allow property is empty. In the list field, every microschema is allowed, but in the single micro node field, no microschema is allowed.

## Reproducer
Create this schema:
```json
{
  "name": "testschema",
  "fields": [
    {
      "name": "single",
      "type": "micronode",
      "allow": []
    },
    {
      "name": "multiple",
      "type": "list",
      "listType": "micronode",
      "allow": []
    }
  ]
}
```

Create any microschema:
```json
{
  "name": "position",
  "fields": [
    {
      "name": "longitude",
      "type": "number"
    },
    {
      "name": "latitude",
      "type": "number"
    }
  ]
}
```
Then follow these steps:
* Create a node with the `single` field set -> results in error
* Create a node with the `multiple` field set -> works

## Expected behaviour and actual behaviour
I expected the same result for the last two requests. I don't think it is defined anywhere what should happen when the allow field is empty.

**Comment by Jotschi** [comment]
Released with 0.31.5
