### ISSUE TITLE
elasticsearch 6.2 support [question]

### ISSUE THREAD

**Issue by unclebean** [gentics/mesh#432]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.x

## Operating System
- Linux
- Windows

## JVM
- Oracle JDK 1.8.0_100

## Problem
Hi Mesh team
First thank you to provide really powerful CMS tool, I have one question want to ask you. 
What's the Elasticsearch supporting version? In the main pom file just mentioned 
**elasticsearch.client.version** is **0.5.0**. So I have a little bit confused. In my team we plan to use **elasticsearch 6.2**. So please let me know if we can contribute anything. 
Thank you!

**Comment by Jotschi** [comment]
@unclebean The client is just a library which we wrote to communicate with ES. We currently run our tests against 6.1.2. I took at look at the changelog for 6.2.0 and found no breaking changes which could affect the integration. I suggest you just try it yourself. I'm going to bump the version in our test suite to the latest version once I'm back from holiday.

Glad that you like Mesh. Let me know if you encounter anything which could be improved.

**Comment by unclebean** [comment]
@Jotschi thank you!
Actually I got **Error: Could not find or load main class org.elasticsearch.bootstrap.Elasticsearch** . When I run demo jar which I downloaded from [getmesh.io](https://getmesh.io/Download) . So I just think maybe that's elasticsearch compatible issue. I will try again, thank you for your quickly response!

**Comment by Jotschi** [comment]
@unclebean I assume you just replaced the elasticsearch folder with the new version? This is not supported. We actually plan to get rid of the "embedded" ES soon.

Instead I suggest that you use docker to start up a dedicated ES instance:
https://github.com/gentics/mesh-compose
I updated the example to use ES 6.2.4.

**Comment by unclebean** [comment]
@Jotschi Since we already have elasticsearch service, so I don't replace anything. **mesh-demo-0.21.1.jar** will connect to http://127.0.0.1:9200 automatically. Anyway thanks for the suggestion. I will try to use docker and dive into the code :)
