### ISSUE TITLE
Application hangs for a long time trying to start elasticsearch when JAVA_HOME is incorrect

### ISSUE THREAD

**Issue by alshain** [gentics/mesh#445]
## Gentics Mesh Version, operating system, or hardware.
mesh-demo-0.21.3

## Operating System
Windows
## JVM
Oracle JDK 1.8.0_151

## Problem

While starting the application, elasticsearch could not be launched because java.exe wasn't found (my JAVA_HOME pointed to an uninstalled JDK)

## Expected behaviour and actual behaviour

Actual: the crash was detected and logged, the software waited for elasticsearch (which couldn't be started) to come  online

Expected: The software shouldn't wait for elasticsearch to come online but terminate instead.

**Comment by Jotschi** [comment]
Thanks for the report. This issue should be resolved with the next release. We however plan to deprecate the embedded ES in the near future and provide ES support as a plugin.

**Comment by Jotschi** [comment]
Fix was released in 0.21.4
