### ISSUE TITLE
Order of elements in a field of type list of micronodes is not preserved (when 40 or more elements)

### ISSUE THREAD

**Issue by cschockaert** [gentics/mesh#469]
## Gentics Mesh Version, operating system, or hardware.
- v0.24.4

## Operating System

- MacOSX

## Problem

A list of micronode in a node is shuffled when 40 or more elements in it:

## Reproducer

Create a simple node schema with 1 field pointing to a LIST of microschema (with for eg one text/number field)

create 39 element in the list
save --> order is preserved

![image](https://user-images.githubusercontent.com/8597973/42644800-c0cd300c-85fc-11e8-9245-7cec2d4e3160.png)

add 1 element (40 element in the list)
![image](https://user-images.githubusercontent.com/8597973/42644817-c7cb396c-85fc-11e8-8344-96f038d46bbd.png)

save --> order is lost
![image](https://user-images.githubusercontent.com/8597973/42644823-cb8995a8-85fc-11e8-8362-b4e928cada90.png)

after some debug in local i see that the micronode list is still in the same order when saving it
but when retreiving it to rest model it's wrong order
perhaps addItem in graph with ferma is bugged after 40 items

## Expected behaviour and actual behaviour

order must be preserved

**Comment by Jotschi** [comment]
This is a known issue and we already have a test to reproduce it. #84 
it is on the roadmap for 1.0. 
The list items are stored without any order and after a certain size the order changes / is mangled.
You may also encounter this problem in other lists (except basic lists like number, boolean, string).
We already have a plan to address this. Thanks for the report.

**Comment by Jotschi** [comment]
Released with 0.21.5
