### ISSUE TITLE
Example code in documentation to update a node is missing "version"

### ISSUE THREAD

**Issue by apagtxmo** [gentics/mesh#476]
## Gentics Mesh Version
- v0.24.0

## Problem
The example in the documentation to update a node of a project is missing the (mandatory) _version_ name/value-pair in the provided JSON code.

## Reproducer
see: https://getmesh.io/docs/beta/raml/#project__nodes__nodeUuid__post

## Expected behaviour and actual behaviour
Is:
`{
  "language" : "en",
  "fields" : {
    ...
  }
}`

Should be:

`{
  "language" : "en",
  "fields" : {
    ...
  },
"version":"2.0"
}`

**Comment by Jotschi** [comment]
Fixed. Thanks for the report.
