### ISSUE TITLE
Replace random uuids in RAML examples

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh#477]
## Gentics Mesh Version, operating system, or hardware.
- v0.24.0

The examples for the RAML documentation are using randomly generated UUIDs. This causes a different RAML every time that Mesh is restarted.

This is annoying for our Typescript interface generator, because this causes a change in git even though nothing has changed.

Please replace them with fixed UUIDs. 

An example can be found here: https://github.com/gentics/mesh/blob/7727d2a18d4df299def939421f84022fe5786466/common/src/main/java/com/gentics/mesh/example/AbstractExamples.java#L56

But there are a lot of other places where random UUIDs are used.

**Comment by Jotschi** [comment]
Will be fixed with #571
