### ISSUE TITLE
Unset properties causes schema migration

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#496]
## Gentics Mesh Version, operating system, or hardware.
- v0.22.1

## Problem

We use a script to upload all local schema files to the server to keep it in sync.
In the local schema, we don't have a `description` property set however, which causes the `schemas/{uuid}/diff` endpoint and subsequently the schema-migration to register changes:

```json
{
	"changes": [
		{
			"operation": "UPDATESCHEMA",
			"properties": {
				"description": null
			}
		}
	]
}
```

So everytime we upload the schema, it'll detect a "change" and perform a new schema migration.

## Reproducer

- Create a Schema without a description field
- Update the schema with the exact same content

## Expected behaviour and actual behaviour

It should detect that there is actually no change and not trigger unneccessary schema migrations.

**Comment by Jotschi** [comment]
I added a dedicated test for this case. It seems that this has been fixed in the meanwhile. The diff is no longer registered. Closing the issue.
