### ISSUE TITLE
Renaming the admin role causes problems

### ISSUE THREAD

**Issue by DevNils** [gentics/mesh#518]
## Gentics Mesh Version, operating system, or hardware.
- v0.26.0

## Operating System
- MacOSX

## JVM
- Oracle JDK 1.8.0_144

## Problem
If you rename the admin role you can not backup the database anymore.

## Reproducer
- Take a fresh mesh and try to backup the database via api/v1/admin/graphdb/backup, it will work
- Go to "roles" in the UI and rename "admin" to something else (I took "superuser")
- Try to backup the database again, it will fail with: "Administration permissions are required."

## Expected behaviour and actual behaviour
I would expect that the backup would work after renaming the admin role.

**Comment by Jotschi** [comment]
Thanks for the report and the reproducer. I can confirm the issue.

**Comment by Jotschi** [comment]
Possible fixes in Gentics Mesh:
## Protect admin elements
* Add protected property to user, role, group of admin and prevent modification of these elements.

## Mark admin role
* Mark the admin role with a dedicated edge and thus don't rely on the name of the role. In this case the special state of this role should be also reflected in the role properties.

**Comment by Jotschi** [comment]
@DevNils
We just released version 1.5.3 which no longer relies on the `admin` role. Instead the users have a dedicated flag which can be toggled to grant admin perms. Additionally it is now possible to restore the admin user permissions and password via ` java -jar mesh-server-1.5.3.jar -resetAdminPassword admin`.
