### ISSUE TITLE
CPU load rises extremely while downloading binaries from mesh

### ISSUE THREAD

**Issue by DevNils** [gentics/mesh#530]
## Gentics Mesh Version, operating system, or hardware.
- v0.24.0
- v0.27.1

## Operating System
- Linux

## JVM
- Comes with docker

## Problem
We deal with relatively large files (around 4GB) in mesh. While downloading a big file, the CPU load of the mesh java process rises to a very high base (around 100%).

## Reproducer
- Upload a big file to a node (around 4GB)
- Download the binary file (with curl e.g.)

## Expected behaviour and actual behaviour
We tried to download the same file directly from apache which caused a CPU load of 5%. The CPU load should not be to high while downloading a file from mesh.

**Comment by Jotschi** [comment]
@DevNils Thanks for the report. I'll profile and check the code. Serving static resources should be a zero-copy operation with nearly no CPU utilization involved.

TODO @Jotschi :
* Check why HttpServerResponse#sendFile is not working as expected
* Add dedicated performance test for large files
* Check why this is not an issue for TVC installation

**Comment by Jotschi** [comment]
@DevNils I made a fix which will hopefully make it into the next release. I'll inform you once the version is available.

**Comment by Jotschi** [comment]
@DevNils I just released 0.27.2 which includes the performance fixes. The new version will also utilize native bindings when run on linux (e.g. docker) to increase HTTP performance. I was able to run downloads with 1.8 GB/s - The CPU load is now much lower. Let me know whether this solves your issue.
