### ISSUE TITLE
Catch with no Log

### ISSUE THREAD

**Issue by sunsus** [gentics/mesh#538]
Please log at least a Debug here, otherwiese you woll newer know if there was a connection problem: 
https://github.com/gentics/mesh/blob/1d8457026af04a9ef170f1b0f148765af3675222/elasticsearch/src/main/java/com/gentics/mesh/search/impl/ElasticSearchProvider.java#L148

**Comment by Jotschi** [comment]
We actually hope to get rid of the whole loop in https://github.com/gentics/mesh/blob/1d8457026af04a9ef170f1b0f148765af3675222/elasticsearch/src/main/java/com/gentics/mesh/search/impl/ElasticSearchProvider.java#L133 - I'll update the error handling and log connection issues in the meanwhile.

**Comment by Jotschi** [comment]
Gentics Mesh will no longer wait for ES. This change has been released with 0.32.0
