### ISSUE TITLE
Website Issue - https://getmesh.io/

### ISSUE THREAD

**Issue by rotexhawk** [gentics/mesh#574]
The website is not loading. https://getmesh.io/

**Comment by Jotschi** [comment]
I can't confirm this. We cross checked this with web services.

* https://downforeveryoneorjustme.com/getmesh.io
* https://www.uptrends.com/tools/uptime

**Comment by Jotschi** [comment]
@rotexhawk What kind of error message are you seeing? DNS or HTTP error?

**Comment by rotexhawk** [comment]
It is working now.
