### ISSUE TITLE
Transforming an image in a node breaks webroot API for that node

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh#599]
## Gentics Mesh Version, operating system, or hardware.
- v0.28.2

## Reproducer
1. Have a schema with a segment field that points to a binary field
2. Create a node of that schema
3. Transform the image using the UI and save the node
4. Try to access the node via webroot API
5. 404 will happen

## Expected behaviour and actual behaviour
I expected the node to be found.

**Comment by Jotschi** [comment]
Released with 0.31.5
