### ISSUE TITLE
LinkResolving with Branch not correct in GraphQL

### ISSUE THREAD

**Issue by patrickhoefer** [gentics/mesh#603]
## Gentics Mesh Version, operating system, or hardware.
- v0.28.2

## Problem
Node in Branch (not latest) containing a Link to another Node in the same branch

```{{mesh.link(762adc0c0f6811e9a373005056a3006d)}}```

Node fetched with `linkType:SHORT` - Link resolves to `"https://domain.com/master/"` and that's not the actual path of the target node (`"path": "/oe/marketing/Page.html"`)

The problem only occurs when the node ist fetched via GraphQL (branch specified in URL)
If you use the nodes endpoint instead (`/api/v1/Iproject/nodes?branch=586af03392064885aaf0339206788568&resolveLinks=short`) the link is correctly resolved.

## Reproducer
* Project with at least 2 Branches
* 2 Nodes in not default/latest branch
* First node lInks to second node
* GraphQL Request to fetch first node

## Expected behaviour and actual behaviour
Resolved Link should be `https://domain.com/oe/marketing/Page.html`

**Comment by philippguertler** [comment]
Fixed by #594 
Will be released in next version.

**Comment by mephinet** [comment]
Released.
