### ISSUE TITLE
Removal of older versions / purge

### ISSUE THREAD

**Issue by mephinet** [gentics/mesh#605]
(forked out of #49)

We need to add a way to remove older versions from the system.

We must keep:

    Draft version's across all releases
    Published version's across all releases

**Comment by Jotschi** [comment]
## Concept

Delete only specific version
```DELETE /api/v1/:projectName/nodes/:uuid/versions/1.0```

Delete all versions of lang 'de'.
```DELETE /api/v1/:projectName/nodes/:uuid/versions?lang=de```

Delete all versions in latest branch
```DELETE /api/v1/:projectName/nodes/:uuid/versions```

Delete in branch only
```DELETE /api/v1/:projectName/nodes/:uuid/versions?branch=test```

Delete all versions in the given subtree of nodes
```DELETE /api/v1/:projectName/nodes/:uuid/versions?recursive=true```

**Comment by npomaroli** [comment]
* Initial Edge should be changed to the oldest NGFC that will remain
* version purge for project (not single nodes)
* purge all (unused) versions or all (unused) versions older than given timestamp
* version purge is done async (job in job list)
* per project setting to "disable" versioning

**Comment by npomaroli** [comment]
purging could be implemented in two transactions
1. "Isolate" NGFCs that will be purged (by moving Initial Edge and has_version)
2. Remove now dangling NGFCs

**Comment by Jotschi** [comment]
https://github.com/gentics/mesh/pull/718

**Comment by Jotschi** [comment]
Tasks

* [ ] Initial Edge should be changed to the oldest NGFC that will remain
* [ ] version purge for project (not single nodes)
* [ ] purge all (unused) versions or all (unused) versions older than given timestamp
* [x] version purge is done async (job in job list)
* [x] per project setting to "disable" versioning
* [ ] handle "disabled" versioning

**Comment by Jotschi** [comment]
We decided not to re-map or remove initial versions. Removing these versions would remove the branch history of the content. We need this history at a later point to apply branch merging. Otherwise the common root version of two branches can't be determined. This root is needed to determine the diff in-between both versions.

**Comment by Jotschi** [comment]
Feature merged
