### ISSUE TITLE
Version in Search-Index

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#607]
## Gentics Mesh Version, operating system, or hardware.
- v0.22.x

## Problem

It appears that the Indexing of Nodes does not properly set the Version. In our index the Version looks like this for example `4ae6d744` instead of `4.0`.
The guess it that it's the Java-Object ID from the JVM at the point of index rather than the actual Version.

**Comment by Jotschi** [comment]
@SiNEXiST The version key does not reference the node version instead it references the document version that is being stored in Elasticsearch. This is not a bug. The version is used to execute the differential ES index sync.
