### ISSUE TITLE
Add micronode list deletion handling

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#609]
Currently micronode deletion will not remove lists:
https://github.com/gentics/mesh/blob/master/core/src/main/java/com/gentics/mesh/core/data/node/impl/MicronodeImpl.java#L113

We should refactor the NGFC delete implementation and move the shared code in the abstract class. NGFC delete should invoke the super method to delete the lists.

Tests and consistency checks for this case have to be added.

**Comment by mephinet** [comment]
tests missing...

**Comment by Jotschi** [comment]
The field delete tests we got cover this case since we now have consistency checks for dangling micronodes.
