### ISSUE TITLE
When calling auth/logout, Set-Cookie does not update the mesh.token cookie value

### ISSUE THREAD

**Issue by michaelbromley** [gentics/mesh#63]
## Gentics Mesh Version, operating system, or hardware.
- [X] v0.9.11

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## JVM
- [x] Oracle JDK 8
- [ ] Open JDK 8

## Problem
When calling `api/v1/auth/logout`, the `Set-Cookie` header attempts to set the `mesh.token` cookie to "deleted", but this does not seem to work in my tests with Chrome 58.

## Reproducer
1. In the demo admin ui, clear any cookies (devtools -> Application -> cookies -> delete)
2. Login as admin. This will return a response including the header:
```
Set-Cookie:mesh.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyVXVpZCI6ImM3NWM4M2U1NzExZDQ2ZDc5YzgzZTU3MTFkMTZkNzhhIiwiaWF0IjoxNDk2ODQxNjQ5LCJleHAiOjE0OTY4NDUyNDl9.jBUCFoRa-QzThDKBsWwh4CiczyqYkYmN5ue4gQiCOvA=; Max-Age=3600; Expires=Wed, 7 Jun 2017 14:20:49 GMT; Path=/
```
3. Note that devtools-> Application -> cookies shows that the `mesh.token` cookie has been set.
4. Log out. This calls `auth.logout` which should set the cookie value to "deleted" as below:
```
Set-Cookie:mesh.token=deleted; Max-Age=0; Expires=Wed, 7 Jun 2017 13:22:20 GMT
```
5. The value of the "mesh.token" cookie remains the same as before logout, rather than being set to "deleted"

**Comment by tpusztaiGentics** [comment]
This has been fixed in #282. If the path of the cookie is set to `Path=/` (the same that was used to set the cookie at login) when deleting the cookie, Chrome will delete the cookie properly.
