### ISSUE TITLE
PDF files with an uppercase extension cannot be opened in Chrome

### ISSUE THREAD

**Issue by wamaithaj** [gentics/mesh#645]
## Gentics Mesh Version, operating system, or hardware.
- v0.22.10

## Problem
- Files with uppercase extentions are not correctly loaded, in this case the pdf file cannot be displayed in chrome.
![image](https://user-images.githubusercontent.com/2248530/52468188-379b9300-2b88-11e9-8865-b306c4cc5f11.png)

## Reproducer
- upload a PDF file with an uppercase extension. 
- download it and observe that the content type is binary.

## Expected behaviour and actual behaviour
- Opening pdf files should be possible even if the extension is uppercase.

**Comment by Jotschi** [comment]
@wamaithaj This is actually a portal bug. But I have added a few extra testcases in mesh to cover this anyhow.

https://github.com/gentics/mesh-portal-framework/blob/eaac705c41db93fd597a44e8953893e052f3c9ae/handler/contenthandler/src/main/java/com/gentics/mesh/portal/content/ContentPathHandler.java#L274
