### ISSUE TITLE
It would be login out automatically after a while

### ISSUE THREAD

**Issue by suihanhbr** [gentics/mesh#659]
I am building a web site by this CMS. And I found the connection will be broke after a while , and get the error message like that:
```
 Error:401 in POST /api/v1/suihanproject/graphql : Unauthorized Info: You are not authorized to access the requested resource.
```

I think it is the mechanism of the CMS to make login out automatically.  But I need the connection available always. Any advice? thank you.

**Comment by suihanhbr** [comment]
I add code like that:
```
interval = new ObservableInterval(55, 55, TimeUnit.MINUTES, Schedulers.computation());
					interval.subscribe((o) -> client.login());

```
It works.

**Comment by Jotschi** [comment]
I suggest that you create an API Token and use this instead of the login. API Tokens will never expire:

https://getmesh.io/docs/authentication/#_api_token

**Comment by suihanhbr** [comment]
> I suggest that you create an API Token and use this instead of the login. API Tokens will never expire:
> 
> https://getmesh.io/docs/authentication/#_api_token

thanks for your suggestion.
