### ISSUE TITLE
Like plugin not returning Content-Type for the JSON responses

### ISSUE THREAD

**Issue by netwarex** [gentics/mesh#660]
## Gentics Mesh Version, operating system, or hardware.
- v0.29.1

## Operating System
- any

## JVM
- Oracle JDK 1.8.0_202-b08

## Problem
Like plugin endpoints returns without Content-Type header, only a Content-Length.

## Reproducer

Request any Like plugin endpoint with GET.

## Expected behaviour and actual behaviour

Content-Type should return "application/json" for JSON responses.

**Comment by Jotschi** [comment]
This should be moved to jira. GH is only for OSS projects.

**Comment by Jotschi** [comment]
Fixed in like-plugin/dev-mesh-update branch.
