### ISSUE TITLE
ETag response header is missing quotes

### ISSUE THREAD

**Issue by berni2288** [gentics/mesh#679]
## Gentics Mesh Version, operating system, or hardware.
- Latest

## Operating System
- Linux

## JVM
- Oracle JDK 1.8.0_191

## Problem

When a binary file is requested from the webroot API, the etag header is not surrounded by " " quotes.
See: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.19

## Reproducer

Do a request to any binary file with the webroot method

## Expected behaviour and actual behaviour

Etag with quotes

**Comment by berni2288** [comment]
Nevermind, I think it was some problem with debugging.

**Comment by Jotschi** [comment]
The ETag values in mesh responses are containing quotes.
