### ISSUE TITLE
Plugin Admin Client uses wrong host

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#715]
The creation of the admin client will correctly not work when the mesh configuration uses host 0.0.0.0 - This host can't be used to connect to. It is only used to bind to.

https://github.com/gentics/mesh/blob/b9e0f91a2091b958a2e255df45cf92a2346c46c3/plugin-api/src/main/java/com/gentics/mesh/plugin/AbstractPluginVerticle.java#L170

**Comment by jdbranham** [comment]
@Jotschi - Looking to get my feet wet in Mesh contribution, and this looks like an easy fix.
I've already signed the CLA and forked the repo - do I create a branch like 'dev-issue-715' and submit a PR? 

Thanks!

**Comment by Jotschi** [comment]
@jdbranham Yes, just open a PR when you are ready. I would check whether it is possible to somehow get the IP of one or more hosts to which the REST API Server was bound:

https://github.com/gentics/mesh/blob/869033bb6e9f2ae001d661fae5f2ec774398f5fd/core/src/main/java/com/gentics/mesh/rest/RestAPIVerticle.java#L190

Maybe this is not possible via the vert.x API. In this case you could change the code to create the socket first and pass it along in the listen call. Let me know if you have any questions.

**Comment by jdbranham** [comment]
Thanks!
If the app is bound to 0.0.0.0 in configuration, then it's implicitly bound to 127.0.0.1
Couldn't the admin client then just connect to 127.0.0.1 when the host string == "0.0.0.0"?

[I might be overlooking something because I've only just started working with Mesh CMS]

**Comment by Jotschi** [comment]
You are right. I think the chances that the host system / container has no 127.0.0.1 are very low. So this would also be a valid solution. I'm looking forward to your PR.
