### ISSUE TITLE
How to add multi-languages?

### ISSUE THREAD

**Issue by Shashi-GS** [gentics/mesh#758]
## Gentics Mesh Version, operating system, or hardware.
- v0.33.0

## Operating System
- Windows

## JVM
- Oracle JDK 1.8.0_100

I want to add french language and other language support for CMS. How do I do it?

**Comment by Jotschi** [comment]
You can add additional languages to the UI by editing the `mesh-ui-config.js` file and update the `availableLanguages` property.

Example `availableLanguages: ['en', 'de', 'fr', 'ru']`

**Comment by Shashi-GS** [comment]
Thank you so much. I am able to get the language.  I have one more question. Is there any way I can use the auto translation based on language selection?

**Comment by Jotschi** [comment]
@Shashi-GS Sorry, there is no auto translate feature in Gentics Mesh. But that's a good idea for a plugin / extension.

**Comment by Shashi-GS** [comment]
Oh Okay! Thank you so much response.

**Comment by Jotschi** [comment]
@Shashi-GS No problem. Have a nice day.
