### ISSUE TITLE
Role parameter in node loading doesn't work

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#781]
##  Problem

In the documentation for [`GET /nodes/{uuid}`](https://getmesh.io/docs/api/#project__nodes__nodeUuid__get), it describes a parameter `role` which can be applied to load the node with the given role instead.

This parameter seems to be completely discarded however and doesn't work.

## Reproducer

* Create a Node
* Assign read permissions to that node
* Login as a User which has permissions to load the node
* Append the `role` query parameter with a uuid of a role which doesn't have permissions (I did it with the `annonymous` role)
* The node is still readable

## Expected behaviour and actual behaviour

It should not be possible to load the node and give you the proper error message for missing permissions.

**Comment by philippguertler** [comment]
The node should be readable, if the current logged in role has access. The `role` query parameter should only add the `rolePerms` property to the response which lists the permissions of that role.

**Comment by SiNEXiST** [comment]
Ah I see. Thanks for clearing that up
