### ISSUE TITLE
Reduce metadata fields from tika binary processing

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh#786]
When indexing binaries to elastic search, Apache Tika is used to extract metadata. Everything that is extracted in this way is written to elastic search. This can cause an unnecessary high amount of fields and data sent, even if most of the data is not used. There should be some way to filter the fields that will be indexed to elastic search.

**Comment by Jotschi** [comment]
We have not a setting which can be used to disable processing and index handling

https://getmesh.io/docs/changelog/#v0.36.4
