### ISSUE TITLE
OptionsLoaderTest.testApplyEnvs fails

### ISSUE THREAD

**Issue by jdbranham** [gentics/mesh#794]
## Gentics Mesh Version, operating system, or hardware.
- v0.36.5-SNAPSHOT [dev branch]

## Operating System
- Windows

## JVM
- Open JDK 11.0.3.7

## Problem
org.gentics.mesh.OptionsLoaderTest.testApplyEnvs fails 

## Reproducer
Fresh checkout of dev branch -> run JUnit tests on org.gentics.mesh.OptionsLoaderTest

## Expected behaviour and actual behaviour
Expected OptionsLoader to use the env variables.  
Actual behavior - the environment variables are not set, the OptionsLoader doesn't use them.

I've fixed this in a branch that uses a contributed JUnit package - 
https://stefanbirkner.github.io/system-rules/#EnvironmentVariables

The dependency looks well maintained, and is able to revert changes after the test, since it uses a JUnit Rule.

I can create a PR with this fix [added dependency], or we can try to understand why the reflective 'set' method in the class is failing and fix it.

**Comment by Jotschi** [comment]
That's odd. The OptionsLoaderTest is passing for me and jenkins. Maybe the failure you are seeing is related to windows. I would however not mind using the lib. I'll check the PR.

**Comment by jdbranham** [comment]
I think you're right about Windows. Maybe even the specific jdk on Windows.

I didn't get the error on Linux when i ran the tests before.
