### ISSUE TITLE
Improve OAuth MappingScript

### ISSUE THREAD

**Issue by patrickhoefer** [gentics/mesh#831]
It would be nice if the mapping Script for OAuth Users could be improved
https://getmesh.io/docs/authentication/#_mapping_script

Currently it's only possible to add a user to a group. 
If a group is not available the automatically created group has no roles set.

Probably we can replace the mapping Script with a Plugin, so a developer has more possibilties to handle OAuth Users:

* Creating groups and roles
* Assigning Roles to Groups
* ...

**Comment by Jotschi** [comment]
Released in 0.38.0
