### ISSUE TITLE
Custom Plugin GraphQL API

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh#837]
# Abstract
I propose a way to let plugins define their own GraphQL API. This API is then integrated into the existing Mesh GraphQL API.

# Example
In this example we have a plugin that fetches weather data. Here is an example request that is integrated in Mesh:

```graphql
{
  pluginApi {
    weatherPlugin {
      weather(city: "Vienna") {
        temperature
        humidity
      }
    }
  }
}
```

As you can see, there is a new property `pluginApi`. In this field, all plugins that provide a GraphQL API are listed here. Mesh fetches the type definition from the plugin and integrates that into this field.

The plugin is free to define whatever type it wants and also defines the data fetchers for each type.

**Comment by Jotschi** [comment]
Implemented with 0.37.0
