### ISSUE TITLE
HTML field behavior question

### ISSUE THREAD

**Issue by digitalseas** [gentics/mesh#841]
## Gentics Mesh Version, operating system, or hardware.
- v0.37.x

## Operating System
- Windows

## JVM
- Oracle JDK 1.8.0_100

## Problem
Thank you for creating the product. I am new to Mesh. It seams the HTML content cannot be displayed, even when the schema specify that the filed is an HTML type. For example, in the demo app, I added a project with description: <b>this is bold text</b>. In the front end, the HTML tags will be treated as a String and shown in page.

I would expect the HTML schema filed will be able to hold and display HTML content because I will use the filed to show some Plot.ly-based charts.

Thank you for the help.

**Comment by digitalseas** [comment]
![2019-08-08 00_20_46-Gentics Mesh Vert x Demo](https://user-images.githubusercontent.com/8967340/62677511-30591480-b974-11e9-9cf3-3ee639ea7f42.jpg)

**Comment by mephinet** [comment]
Hi @digitalseas! If you take a look at https://demo.getmesh.io/mesh-ui/ (login with admin/admin), and edit one vehicle's details, the description field is of type HTML. As you can see, the textarea will transform into a WYSIWYG editor when you focus it:
![image](https://user-images.githubusercontent.com/1292953/62699584-2b31af00-b9e0-11e9-88e6-592f4388a4a7.png)
So you should never see the plain HTML tags.
If this isn't working for you on https://demo.getmesh.io , can you please check the javascript console and post its contents?

**Comment by digitalseas** [comment]
Hi @mephinet . Thank you for the quick response. 
This is the problem that I mentioned. 
We can add HTML tags in the WYSIWYG editor, or directly feed it to the database for the HTML field, but the output on the frondend page is not interpreted as HTML content. 
Please see the front end that has the problem here:
https://demo.getmesh.io/demo/product/fc3c85be82584ae2bc85be82588ae2b0
![2019-08-08 13_33_32-Gentics Mesh Angular Demo](https://user-images.githubusercontent.com/8967340/62728854-61702e00-b9e2-11e9-9de6-a0e04831af2f.jpg)

On the WYSIWYG editor it is shown correctly though.
![2019-08-08 13_31_27-Mesh Admin UI](https://user-images.githubusercontent.com/8967340/62728898-7b117580-b9e2-11e9-8e75-39445b78ec49.jpg)

Thank you.

**Comment by digitalseas** [comment]
This is another example, which suppose to embed a piece of Javascript in the HTML. But the scripts are shown directly in the frontend.

![2019-08-08 13_56_44-Gentics Mesh Vert x Demo](https://user-images.githubusercontent.com/8967340/62729955-a6955f80-b9e4-11e9-81c3-6ed06b435bdb.jpg)

**Comment by Jotschi** [comment]
I'm not an expert in angular but I think this is purely a front-end issue. Angular seems to escape HTML.
See https://stackoverflow.com/questions/15754515/how-to-render-html-with-angularjs-templates

**Comment by digitalseas** [comment]
I'm using the Vert.x frontend. It has the same issue as the Angular frontend. Below is the Json response from the Mesh core API before it is consumed by the front. It looks ok. But when it is consumed by the frond, the tags are escaped. I am not familiar with whole platform, especially the frontend tech, so not sure which step to fix this. 

  "container" : false,
  "displayField" : "name",
  "displayName" : "TEST-TEST-4",
  "fields" : {
    "slug" : "test-4",
    "name" : "TEST-TEST-4",
    "description" : "    **<script>**\n        var target_target = document.getElementById('target');\n        var layout = {\n    title: 'Average retail price for champagnes by year and rating',\n    height: 600,\n    width: 800,\n    xaxis: {\n    title: 'highest pro score',\n    },\n\n    yaxis: {\n    title: 'year',\n    },\n\n};\n\r\nvar trace0 =\n{\nx: ['92','90','92','91','93'],\ny: ['2008','null','null','2007','2006'],\nmarker: {\n    size: [35.495, 19.14, 57.99, 29.495, 27.995],\n},\nmode: 'markers',\nxaxis: 'x',\nyaxis: 'y',\ntype: 'scatter',\nname: '',\n};\r\n\r\n        var data = [ trace0];\r\nPlotly.newPlot(target_target, data, layout);            **</script>**\n"
  },

**Comment by Jotschi** [comment]
@digitalseas Not sure what causes those script tags. 

Just did a quick test. I updated the description and fetched the value with GraphQL:

https://demo.getmesh.io/api/v2/demo/graphql/browser/#query=%7B%0A%20%20node(uuid%3A%20%22fc3c85be82584ae2bc85be82588ae2b0%22)%20%7B%0A%20%20%20%20...%20on%20vehicle%20%7B%0A%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A

You just get the JSON with the html back. No fancy magic involved. Gentics Mesh Server does not escape the code. This might be different on the frontend. You need to handle it accordingly.

**Comment by digitalseas** [comment]
Thanks a lot for the tips @Jotschi . I figured this out. Just putting the solution here in case anyone search it in the future.
I used the Vert.x+handlebars frontend. In the handlebar template xxxx.hbs, you will need three curly braces to prevent HTML escaping, example:
 {{{ data.node.fields.description }}}
