### ISSUE TITLE
New Plugin system breaks GraphQL code generation

### ISSUE THREAD

**Issue by mephinet** [gentics/mesh#842]
When using https://graphql-code-generator.com, the execution of all plugins I tested (typescript, fragment-matcher, introspection) fails with:
> Type PluginAPIType must define one or more fields.

This only happens with Mesh v. 0.37.x and 0.38.0 - with 0.36.8, codegeneration works fine - so it's probably caused by the new plugin system that was introduced with 0.37.0...

Seen with "@graphql-codegen/cli@^1.5.0" with this codegen.yaml: 
```overwrite: true
schema:
 - http://localhost:8080/api/v2/.../graphql:
    headers:
      Authorization: Bearer  ...
generates:
  src/generated/fragmentTypes.json:
    plugins:
      - fragment-matcher
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "fragment-matcher"
```
when executing `graphql-codegen --config codegen.yml`.

**Comment by Jotschi** [comment]
That should be easy to fix. We'll just omit the pluginApi field if there are no plugins to access.
