### ISSUE TITLE
How to add another language for content in container language switcher ?

### ISSUE THREAD

**Issue by joao-parana** [gentics/mesh#848]
## Gentics Mesh Version, operating system, or hardware.
- v0.39.1

## Operating System
- All

## JVM
- "11.0.1" 2018-10-16 LTS

## Problem

I need add content in Portuguese ('pt') using Mesh UI 

## Reproducer

Open Mesh UI and try to translate an existent content.

## Expected behaviour and actual behaviour

Portuguese doesn't appear on dialog.

**Comment by Jotschi** [comment]
@joao-parana  Please check the `mesh-ui-config.js` file. You need to edit the `availableLanguages` property and add 'pt'.

**Comment by joao-parana** [comment]
Tanks @Jotschi but where can I find this file `mesh-ui-config.js` ?

**Comment by Jotschi** [comment]
@joao-parana If you use docker you need to mount the config folder:

```docker run -v $PWD/config:/config  -p 8080:8080 gentics/mesh-demo:0.39.1```

Otherwise a `config` folder will be created on startup of Gentics Mesh which contains the file.
