### ISSUE TITLE
Elasticsearch term query on user emailadress return nothing

### ISSUE THREAD

**Issue by dangrth** [gentics/mesh#858]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.x

## Operating System
- MacOSX

## JVM
- OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)

## Problem

Using /api/v2/search/users, when I run the query
`{
	"query": {
		"match": {
			"emailaddress": "myemail@gmail.com"
		}
	}
}`

It returns my email, but also several others, since it is a fuzzy search.

But if I run
`{
	"query": {
		"term": {
			"emailaddress": "myemail@gmail.com"
		}
	}
}`

I get nothing, even though there is an exact match.

## Reproducer

* Create a user with a given email address
* Perform an Elasticsearch term query on it

## Expected behaviour and actual behaviour

I should receive a reply with a single user, the one with the exact match.

My guess is that the mapping does not store the email but parses it through an analyzer so I can't get an exact match.

**Comment by Jotschi** [comment]
@dangrth 

Just tested this on demo.getmesh.io:

```
> POST /api/v1/search/users HTTP/1.1
> Host: demo.getmesh.io
> User-Agent: insomnia/6.2.0
> Cookie: mesh.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyVXVpZCI6IjQxN2JhMjNjNzA3MDRhZjliYmEyM2M3MDcwZGFmOTk2IiwiaWF0IjoxNTY2NDExNDY5LCJleHAiOjE1NjY0MTUwNjl9.vM8SQiyBisBzWykBEyiFiRuug4cSz0BrstEGjRecZ_M
> Content-Type: application/json
> Accept: */*
> Content-Length: 72
| {
| 	"query": {
| 		"term": {
| 			"emailaddress": "test@gentics.com"
| 		}
| 	}
| }
```

It returns the specific user. Term query is the right choice here since the emailaddress field is added as `keyword` field to Elasticsearch.

The record will not be returned if your client user is lacking read permission on the user. Maybe thats the issue you are having?

**Comment by Jotschi** [comment]
Let me know if you need further help with this. I'm closing the issue so far.
