### ISSUE TITLE
OAuth2 Config over Environment Variables: Credentials/Secret missing

### ISSUE THREAD

**Issue by patrickhoefer** [gentics/mesh#859]
## Gentics Mesh Version, operating system, or hardware.
- v0.39.2

It would be nice if it's possible to configure all OAuth2 Config Parameters over Docker ENV Variables.

https://getmesh.io/docs/administration-guide/#_environment_variables

Unfortunately the client secret (credentials - secret) is currently missing
https://getmesh.io/docs/authentication/#_oauth2

**Comment by Jotschi** [comment]
Could be enhanced in combination with #854

**Comment by Jotschi** [comment]
The client secret is not needed for OAuth2 integration in Gentics Mesh.

**Comment by Jotschi** [comment]
OAuth handling has been reworked in 0.41.0
