### ISSUE TITLE
Column level permissions

### ISSUE THREAD

**Issue by maxbl4** [gentics/mesh#864]
Hi, here is my use-case. I would like to allow any registered user to fill in a registration form for event. The form includes private information, like phone number, email, etc
I would like to show a list of filled form results to everyone publicly, but to include only part of columns, so all columns are visible to admin users and subset is visible to normal users. In my mind, this would be possible to achieve with column level permissions. But it seems, mesh does not support such thing.
Maybe there is a workaround?

**Comment by mephinet** [comment]
Hi @maxbl4, did you consider splitting the information into two nodes? e.g. a Registration schema and a RegistrationDetail schema - with Registration holding a reference to RegistrationDetail? Then you can assign different permissions to these two nodes. Your GraphQL query can easily follow the reference, and will only return data if the permissions allow.
While this could be considered to be a work-around ;-) I think it solves your use-case nicely! Do you agree?

**Comment by Jotschi** [comment]
You want field level permissions. Unfortunately this is not yet possible. There is however the idea to add permission checks when loading referenced nodes. This way you could place your private info in an extra node which has just read permissions for the specific user role.

I think for REST this is still open:
https://github.com/gentics/mesh/blob/f379727b5feb5043175be66f9d701c1cbb7700f1/core/src/main/java/com/gentics/mesh/core/data/node/field/impl/NodeGraphFieldImpl.java#L55

For GraphQL it is already implemented.

**Comment by maxbl4** [comment]
Thanks for replies. I'm quite new to the mesh project and currently evaluating which CMS to use. This feature is basically the only missing requirement for me. I will explore how I can split content into nodes. Thanks for the idea.

**Comment by mephinet** [comment]
@maxbl4  you're welcome - if you have any other questions, feel free to join us at https://gitter.im/gentics/mesh
