### ISSUE TITLE
Pagination on Vert.x and Handlebars front-end

### ISSUE THREAD

**Issue by digitalseas** [gentics/mesh#871]
I am trying to figure out how to do pagination on the Vert.x and Handlebars example: https://github.com/gentics/mesh-vertx-example. 

I already know how to acquire the paging information to the front, such as page, totalCount, pageCount, size, perPage, hasNextPage etc. However, I still feel very confused on how to send the paging parameters to the server to move to other pages, such as page=3 etc. If there is any reference on how to implement this on the Vert.x and Handlebars example, please point me to the right direction.
Thank you.

**Comment by Jotschi** [comment]
In the master branch I have update the mesh-vertx-example to use Mesh 0.40.0 and Vert.x 3.8.0.

In the dev-paging branch I added a draft on how to handle paging with Vert.x and Mesh:

https://github.com/gentics/mesh-vertx-example/tree/dev-paging

The categories can now be paged via:
http://localhost:3001/automobiles?page=20

I did not yet render the full paging links in the template but this should be easy to do. The graphql already returns the fields whether a next page or previous page exists.

**Comment by digitalseas** [comment]
That's wonderful! Thank you so much for the help, Johannes.

**Comment by digitalseas** [comment]
Based on Jotschi's updated version, I implemented the pagination using the jquery-bootpag.

In the base.hbs, add, jquery, bootstrap, and jquery-bootpag js .

In the productList.hbs,  add:



**<p id="content">Dynamic page content</p>
<p id="pagination-reviews-top"></p>
<script>

	$('#pagination-reviews-top').bootpag({
	    total: {{data.node.products.pageCount}},          // total pages
	    page: 1,           // default page
	    maxVisible: 10,     // visible pagination
	    firstLastUse: true,
    	    first: 'First',
    	    last: 'Last',
	    href:"?page=\{{number}}",
	    leaps: true         // next/prev leaps through maxVisible
		}).on("page", function(event, num){
	    $("#content").html("Page " + num); // or some ajax content loading...
	    // ... after content load -> change total to 10
	    $(this).bootpag({total: 10, maxVisible: 10});
	});
		
</script>**

Final results: 
![2019-09-05 11_27_33-Gentics Mesh Vert x Demo](https://user-images.githubusercontent.com/8967340/64360804-ce221c80-cfd0-11e9-8426-f117f2699804.jpg)
