### ISSUE TITLE
Adding and publishing nodes does sometimes not show them

### ISSUE THREAD

**Issue by marvin-w** [gentics/mesh#882]
## Gentics Mesh Version, operating system, or hardware.
- v0.40.3

## Operating System
- Linux (Docker Compose)

## Problem

After adding new nodes and publishing them they are not shown in the overview.

Reproduce:
* Create new schema
* Assign schema to project
* Create a new node of that schema type
* The node doesn't appear (sometimes)

Workaround:
Redo the complete process - slowly - then it mostly works.

## Expected behaviour and actual behaviour

The nodes should be shown right after adding/publishing them.

**Comment by Jotschi** [comment]
I suspect that the UI is not showing the nodes since the search index is not yet updated or flushed. The new UI will no longer rely on the search index to show the nodes.

**Comment by marvin-w** [comment]
I believe that is excactly the case. After about a minute or two the nodes suddenly started to appear again.

As the behaviour will change in the new UI I'm fine with this ticket being closed. I'll report a new one once the new UI ships and there still are issues - which I doubt.
