### ISSUE TITLE
Okta JWT fails to decode

### ISSUE THREAD

**Issue by jdbranham** [gentics/mesh#898]
## Gentics Mesh Version, operating system, or hardware.
- v1.0.2

## Operating System
- MacOSX
[mesh is running in Docker]

## JVM
- Oracle JDK 1.8.0_211

## Problem
An exception is thrown when using a JWT from Okta [RS256] . 

## Expected behaviour and actual behaviour 

Expect the JWT to be validate, but instead it fails with this exception - 

``` 
java.lang.RuntimeException: Algorithm not supported
	at io.vertx.ext.jwt.JWT.decode(JWT.java:280)
	at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.authenticate(JWTAuthProviderImpl.java:122)
	at com.gentics.mesh.auth.provider.MeshJWTAuthProvider.authenticateJWT(MeshJWTAuthProvider.java:90)
	at com.gentics.mesh.auth.handler.MeshJWTAuthHandler.handleJWTAuth(MeshJWTAuthHandler.java:152)
	at com.gentics.mesh.auth.handler.MeshJWTAuthHandler.handle(MeshJWTAuthHandler.java:89)
	at com.gentics.mesh.auth.MeshAuthChain.lambda$secure$0(MeshAuthChain.java:40) 
....
```

https://github.com/vert-x3/vertx-auth/blob/3.8.0/vertx-jwt/src/main/java/io/vertx/ext/jwt/JWT.java#L280

I've validated the JWT here, and it seems to decode properly - 
https://jwt.io/ .

**Comment by Jotschi** [comment]
This message gets logged when the JWT handler can't decode the JWT from Okta. In mesh a chain of handlers will be used to validate the token. First the regular JWT handler tries to decode the token. This fails (expected). Next the OAuth handler tries to decode the token. This should work since the JWK was specified.

The error message should however not pollute the log.

# Tasks

* [ ] Unify JWTHandler and OAuth handler so that only a single JWT instance will be used to decode the token. __or__ change the logger for the error to debug  / trace.

**Comment by jdbranham** [comment]
I'm afk right now, but i think the error was at the debug level. I had turned up logging to get more info.

Are you suggesting the decode only failed in the first handler, but succeeded subsequently?

If so, maybe the role mapping just needs to be completed for mesh to create the user on login.

**Comment by jdbranham** [comment]
I've tried creating a custom Authentication service plugin for Okta, but only the plugin `initialize()` is called.  
The other methods like `mapToken`, `acceptToken`, and `getPublicKeys` aren't called.

In my test case, I can authenticate successfully with Okta, but an authenticated call to Mesh still shows "anonymous" as the user -

```
// 1. Login the user
		AuthenticationResponse response = authClient.authenticate(username, password.toCharArray(), null, ignoringStateHandler);
		
		Assert.assertThat(response.getStatus(), is(AuthenticationStatus.SUCCESS));
		
		String token = response.getIdToken(); //.getString("access_token");
		restClient().setAPIKey(token);
		System.out.println("Login Token:\n" + mapper.writeValueAsString(response));

		// 2. Invoke authenticated request
		UserResponse me = call(() -> restClient().me());
		assertEquals(username, me.getUsername());
		assertEquals(username, me.getEmailAddress());
		assertEquals(mappedFirstName, me.getFirstname());
		assertEquals(mappedLastName, me.getLastname());
		String uuid = me.getUuid();
```

**Comment by jdbranham** [comment]
I was passing the id_token in my test - passing the access_token now, and I can reproduce the earlier exception [which may be valid, I'm still verifying]

**Comment by jdbranham** [comment]
I've made some progress trying to track the bug down, but I still don't know why it's failing.
There's an exception getting swallowed here. Thrown from line 122. 
![image](https://user-images.githubusercontent.com/2660839/66882279-6c6dae80-ef8f-11e9-80bd-e7218a727201.png)

According to the error, the Signature is invalid, but it seems to be valid when I use the same access token on my Spring Boot gateway app.

**Comment by jdbranham** [comment]
Found the problem!!!!!

I noticed the token's "kid" parameter in the header, did not have a matching "kid" in the public key list.
I was using the wrong authorization servers JWKs... wow. Heh.

I had this -
https://dev-xxxxxx.okta.com/oauth2/v1/keys

When it should have been this -
https://dev-xxxxxx.okta.com/oauth2/default/v1/keys

Hope this helps someone else.
