### ISSUE TITLE
Nice URL Support

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#90]
It should be possible to store a nice URL for each node. This URL can be used to serve the node with the specified path. Thus it acts similar to an alias.

We need to ensure that there are no conflicts between Nice URL's and regular Webroot URL's.

* [x] Tests (versioning, fallback)
* [x] Tests (graphql)
* [x] Docs
* [x] UI
* [x] Changelog
* [x] Implementation
* [x] Demo examples
* [x] Thirdparty support

**Comment by Jotschi** [comment]
# Options 

## Add additional schema field

```json
{
   "name": "content",
   "displayField" : "name",
   "segmentField" : "slug",
   "urlField" : "nice_url",
…
}
```
## Replace segmentField with new config element

```json
{
   "name": "content",
   "displayField" : "name",
   "url" {
      "segmentKey" : "slug",
      "pathKey" : "path"
   }
…
}
```

**Comment by Jotschi** [comment]
* [ ] Tests
* [ ] Docs
* [ ] Changelog
* [ ] Implementation
* [ ] Thirdparty support

**Comment by Jotschi** [comment]
@aschauerhuber 

Is "urlFields" okay for you? 

Other options:

* niceUrlFields
* directUrlFields
* pathFields
* nicePathFields
* shortUrlFields
* shortPathFields

**Comment by aschauerhuber** [comment]
I'd go for urlFields, if we plan to support different kinds of URLs (nice URLs, short URLs)

Outlook für iOS<https://aka.ms/o0ukef> beziehen



On Wed, Oct 25, 2017 at 10:19 AM +0200, "Johannes Schüth" <notifications@github.com<mailto:notifications@github.com>> wrote:


@aschauerhuber<https://github.com/aschauerhuber>

Is "urlFields" okay for you?

Other options:

  *   niceUrlFields
  *   directUrlFields
  *   pathFields
  *   nicePathFields
  *   shortUrlFields
  *   shortPathFields
