### ISSUE TITLE
Access Gentics mesh over Domain name.

### ISSUE THREAD

**Issue by sambhuva** [gentics/mesh#906]
## Problem
 is there any way to host gentics mesh over secure domain name?
e,g; https://genticmesh.test.com [how to bind domain name for gentics mesh]

**Comment by Jotschi** [comment]
@sambhuva You need a reverse proxy to terminate SSL when using Gentics Mesh. I would recommend to use nginx or traefik (https://docs.traefik.io/providers/docker/).

**Comment by sambhuva** [comment]
but don't want to use Nginx or Another proxy server.
is there any way to modify the mesh.yml and access from outside the network.
 
currently, it is accessible by IP address but I need to access through Domain name.

**Comment by Jotschi** [comment]
@sambhuva I think this has nothing to do with the way mesh works. You need to use a domain name registry to setup an A record for your IP.

**Comment by sambhuva** [comment]
@Jotschi thank you, it's working fine.
but I have another concern related to a wildcard certificate.
I need to configure over wildcard certificate.
like https://_genticmesh_.**abcd.com**
