### ISSUE TITLE
wildcard certificate

### ISSUE THREAD

**Issue by sambhuva** [gentics/mesh#925]
I need to configure over wildcard certificate.
like https://genticmesh.abcd.com

**Comment by bernhardriegler** [comment]
This is not a mesh related issue. Please do contact your hosting provider or if you do host yourself do a quick research on how to set this up.
https://www.google.com/search?q=how+to+configure+wildcard+certificates

Handling the certificate setup for your domain is out of scope for Gentics Mesh.
