### ISSUE TITLE
Refactor / Add DAO API layer in Mesh

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#942]
It would be useful to add / refactor the DAO API layer in Gentics Mesh. This layer could be used to implement a clean version of the Mesh local client.

* Graph API - Ferma Model Classes (`UserImpl`)
* **(NEW) - Mesh DAO API**
* REST Handlers
* REST Endpoint
* HTTP Sever

Local clients and plugins could make use of the DAO layer to directly interface with Mesh.

## Questions:

* Do we want to create dedicated interfaces for this layer which we use for a public API?
* The DAO layer needs to be HTTP agnostic. This means the REST Handlers need to extract the http relevant information and provide it to the DAO layer. How could this be done? Should we keep using a HTTP agnostic context class (similar to `ActionContext`).
* Should code like `UserImpl#transformToREST` should be moved to `UserDAOImpl#toPOJO(User user)`?

**Comment by philippguertler** [comment]
All operations of the new Mesh API should be asynchronous (i.e. returning RxJava Objects). This way the user of the API can always choose between synchronous and asychronous execution.
