### ISSUE TITLE
Graphql browser doesn't load

### ISSUE THREAD

**Issue by digitalseas** [gentics/mesh#944]
Hi,
I want to test a few graphql queries on my locally installed Mesh CMS (V1.2.1). But when I tried to open the address on the web browser, I can only see the page showing "loading" without really loading the graphql browser. Please help. Thank you!

UML used: http://localhost:8080/api/v2/demo/graphql/browser/

![2019-11-24 00_10_20-Mozilla Firefox](https://user-images.githubusercontent.com/8967340/69490530-14a84a00-0e4f-11ea-924d-6c794ee21fed.jpg)

**Comment by Jotschi** [comment]
Which browser are you using? Do you get any errors in your browser console?

**Comment by digitalseas** [comment]
Thanks, Jotschi.
Same error in all three major browsers (Chrome, Firefox, Edge). It looks like that React has a problem for rendering GraphQL:

![image](https://user-images.githubusercontent.com/8967340/69502096-131f6600-0ed1-11ea-8550-f0f8f2fe04cd.png)

JS line 111:

![image](https://user-images.githubusercontent.com/8967340/69502117-2fbb9e00-0ed1-11ea-99df-45d3c16bb3b4.png)

The demo hosted on your server works totally fine. Just not working on my local install.

**Comment by Jotschi** [comment]
Can you give me a list of the names of schemas, microschemas that you are using? Maybe the schema name contains an invalid character and thus breaks the introspection query that is needed to generate the graphiql browser page.

**Comment by Jotschi** [comment]
I'm closing the issue due to missing information. Let me know if you need further help with this. The schema name conflict issue is tracked in another issue.
