### ISSUE TITLE
An empty binary associated to a node will cause a false positive in consistency check

### ISSUE THREAD

**Issue by cschockaert** [gentics/mesh#967]
## Gentics Mesh Version, operating system, or hardware.
- v1.0.2

## Operating System
- Linux

## Problem
We got a node, which has in his version history an empty binary:

calling consistency check/repair will report a problem (false positive) and do nothing:

## Reproducer
I dont know how, but it's in our production environment, perhaps someone uploaded an empty file to the node. (this has been made with the old ui)

## Expected behaviour and actual behaviour

No false positive, or reject upload of an empty file to a node?

```
"inconsistencies" : [ {
    "description" : "The binary has no valid size specified",
    "severity" : "LOW",
    "elementUuid" : "e554e0b199f2456094e0b199f2756018",
    "repaired" : false,
    "repairAction" : "NONE"
  }
```

![image](https://user-images.githubusercontent.com/8597973/70342140-b7e85e80-1854-11ea-916c-11d24401763c.png)

**Comment by Jotschi** [comment]
TODO: 
* [ ] Update consistency check and allow 0 file size and/or also check the actual file size on disk.

**Comment by Jotschi** [comment]
Fixed within https://github.com/gentics/mesh/pull/1078 - Change will be included in the next release. Thanks for reporting.
